# Generated by slsa-autotools scan.yml
# https://github.com/lee-mcfaul2/slsa-autotools @ 0c78366c0d432b1721b72f4e1a82ab4bea5b17cc
#
# Every apt package below is pinned to both an exact version
# and the SHA256 of its .deb as served by
# snapshot.ubuntu.com at 20260425T120000Z. Any drift in the
# served bytes will fail the sha256sum check at image build.
#
# This file is regenerated by scan.yml whenever it is run.
# Hand edits are preserved through the next run only if you
# re-run scan.yml yourself; otherwise a fresh run will
# overwrite. Editing individual SHA256 values is safe — the
# verification step is purely local to this file.

FROM ubuntu@sha256:5e275723f82c67e387ba9e3c24baa0abdcb268917f276a0561c97bef9450d0b4

ENV DEBIAN_FRONTEND=noninteractive

# Step 1: bootstrap ca-certificates from the default HTTP
# archive so we can reach snapshot.ubuntu.com over HTTPS.
RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends ca-certificates

# Step 2: redirect apt to the pinned snapshot. All later
# apt traffic is immutable indefinitely.
RUN set -eu \
 && printf '%s\n' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260425T120000Z/ resolute main restricted universe multiverse' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260425T120000Z/ resolute-updates main restricted universe multiverse' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260425T120000Z/ resolute-security main restricted universe multiverse' \
    > /etc/apt/sources.list \
 && rm -f /etc/apt/sources.list.d/*.sources /etc/apt/sources.list.d/*.list \
 && apt-get update -qq

# Step 3: download each pinned .deb, verify its SHA256,
# then install. A single RUN so failure aborts the layer
# atomically. Packages are deduplicated and sorted.
RUN set -eux \
 && mkdir -p /tmp/debs && cd /tmp/debs \
 && apt-get download \
      autoconf=2.72-3.1ubuntu2 \
      automake=1:1.18.1-3build1 \
      autotools-dev=20240727.1build1 \
      base-passwd=3.6.8 \
      bash=5.3-2ubuntu1 \
      binutils=2.46-3ubuntu2 \
      binutils-common=2.46-3ubuntu2 \
      binutils-x86-64-linux-gnu=2.46-3ubuntu2 \
      bison=2:3.8.2+dfsg-1build4 \
      bubblewrap=0.11.1-1 \
      bzip2=1.0.8-6build2 \
      ca-certificates=20260223 \
      comerr-dev=2.1-1.47.2-3ubuntu4 \
      coreutils-from-uutils=0.0.0~ubuntu25 \
      cpio=2.15+dfsg-2.1 \
      cpp=4:15.2.0-5ubuntu1 \
      cpp-15=15.2.0-16ubuntu1 \
      cpp-15-x86-64-linux-gnu=15.2.0-16ubuntu1 \
      cpp-x86-64-linux-gnu=4:15.2.0-5ubuntu1 \
      curl=8.18.0-1ubuntu2 \
      dash=0.5.12-12ubuntu3 \
      debconf=1.5.92 \
      debianutils=5.23.2build1 \
      diffutils=1:3.12-1 \
      dpkg=1.23.7ubuntu1 \
      e2fsprogs=1.47.2-3ubuntu4 \
      file=1:5.46-5build2 \
      findutils=4.10.0-3build2 \
      fontconfig=2.17.1-3ubuntu1 \
      fontconfig-config=2.17.1-3ubuntu1 \
      fonts-urw-base35=20200910-8build1 \
      g++=4:15.2.0-5ubuntu1 \
      g++-15=15.2.0-16ubuntu1 \
      g++-15-x86-64-linux-gnu=15.2.0-16ubuntu1 \
      g++-x86-64-linux-gnu=4:15.2.0-5ubuntu1 \
      gawk=1:5.3.2-1ubuntu1 \
      gcc=4:15.2.0-5ubuntu1 \
      gcc-15=15.2.0-16ubuntu1 \
      gcc-15-base=15.2.0-16ubuntu1 \
      gcc-15-x86-64-linux-gnu=15.2.0-16ubuntu1 \
      gcc-16-base=16-20260322-1ubuntu1 \
      gcc-x86-64-linux-gnu=4:15.2.0-5ubuntu1 \
      gettext=0.23.2-1 \
      gettext-base=0.23.2-1 \
      ghostscript=10.06.0~dfsg-3ubuntu1 \
      gir1.2-freedesktop=1.86.0-6build1 \
      gir1.2-freedesktop-dev=1.86.0-6build1 \
      gir1.2-gdkpixbuf-2.0=2.44.5+dfsg-4ubuntu1 \
      gir1.2-glib-2.0=2.88.0-1 \
      gir1.2-glib-2.0-dev=2.88.0-1 \
      gir1.2-gly-2=2.1.1+ds-0ubuntu1 \
      gir1.2-harfbuzz-0.0=12.3.2-2 \
      gir1.2-pango-1.0=1.57.0-1 \
      gir1.2-rsvg-2.0=2.61.3+dfsg-3 \
      girepository-tools=2.88.0-1 \
      git=1:2.53.0-1ubuntu1 \
      git-man=1:2.53.0-1ubuntu1 \
      glycin-loaders=2.1.1+ds-0ubuntu1 \
      glycin-thumbnailers=2.1.1+ds-0ubuntu1 \
      gnu-coreutils=9.7-3ubuntu2 \
      grep=3.12-1 \
      gzip=1.14-1~exp2ubuntu1 \
      hostname=3.25build1 \
      icu-devtools=78.2-2ubuntu1 \
      init-system-helpers=1.69 \
      krb5-multidev=1.22.1-2ubuntu4 \
      libacl1=2.3.2-2 \
      libaom3=3.13.1-2 \
      libasan8=16-20260322-1ubuntu1 \
      libatomic1=16-20260322-1ubuntu1 \
      libattr1=1:2.5.2-4 \
      libaudit-common=1:4.1.2-1build1 \
      libaudit1=1:4.1.2-1build1 \
      libavahi-client3=0.8-18ubuntu1 \
      libavahi-common-data=0.8-18ubuntu1 \
      libavahi-common3=0.8-18ubuntu1 \
      libbinutils=2.46-3ubuntu2 \
      libblkid-dev=2.41.3-3ubuntu2 \
      libblkid1=2.41.3-3ubuntu2 \
      libbrotli-dev=1.2.0-3build1 \
      libbrotli1=1.2.0-3build1 \
      libbsd0=0.12.2-2build2 \
      libbz2-1.0=1.0.8-6build2 \
      libbz2-dev=1.0.8-6build2 \
      libc-bin=2.43-2ubuntu2 \
      libc-dev-bin=2.43-2ubuntu2 \
      libc-gconv-modules-extra=2.43-2ubuntu2 \
      libc6=2.43-2ubuntu2 \
      libc6-dev=2.43-2ubuntu2 \
      libcairo-gobject2=1.18.4-3 \
      libcairo-script-interpreter2=1.18.4-3 \
      libcairo2=1.18.4-3 \
      libcairo2-dev=1.18.4-3 \
      libcap-ng0=0.8.5-4build5 \
      libcap2=1:2.75-10ubuntu2 \
      libcc1-0=16-20260322-1ubuntu1 \
      libcdt-dev=14.1.2-1ubuntu1 \
      libcdt6=14.1.2-1ubuntu1 \
      libcgraph-dev=14.1.2-1ubuntu1 \
      libcgraph8=14.1.2-1ubuntu1 \
      libcom-err2=1.47.2-3ubuntu4 \
      libcrypt1=1:4.5.1-1 \
      libctf-nobfd0=2.46-3ubuntu2 \
      libctf0=2.46-3ubuntu2 \
      libcups2t64=2.4.16-1ubuntu1 \
      libcurl3t64-gnutls=8.18.0-1ubuntu2 \
      libcurl4-openssl-dev=8.18.0-1ubuntu2 \
      libcurl4t64=8.18.0-1ubuntu2 \
      libdatrie-dev=0.2.14-1 \
      libdatrie1=0.2.14-1 \
      libdb5.3t64=5.3.28+dfsg2-10ubuntu1 \
      libdbus-1-3=1.16.2-2ubuntu4 \
      libdebconfclient0=0.280ubuntu1 \
      libdeflate-dev=1.23-2ubuntu1 \
      libdeflate0=1.23-2ubuntu1 \
      libdjvulibre-dev=3.5.29-1 \
      libdjvulibre-text=3.5.29-1 \
      libdjvulibre21=3.5.29-1 \
      libelf1t64=0.194-4 \
      liberror-perl=0.17030-1 \
      libevent-2.1-7t64=2.1.12-stable-10build2 \
      libexpat1=2.7.4-1 \
      libexpat1-dev=2.7.4-1 \
      libext2fs2t64=1.47.2-3ubuntu4 \
      libffi-dev=3.5.2-4 \
      libffi8=3.5.2-4 \
      libfftw3-bin=3.3.10-2fakesync1build3 \
      libfftw3-dev=3.3.10-2fakesync1build3 \
      libfftw3-double3=3.3.10-2fakesync1build3 \
      libfftw3-long3=3.3.10-2fakesync1build3 \
      libfftw3-quad3=3.3.10-2fakesync1build3 \
      libfftw3-single3=3.3.10-2fakesync1build3 \
      libfontconfig-dev=2.17.1-3ubuntu1 \
      libfontconfig1=2.17.1-3ubuntu1 \
      libfontenc1=1:1.1.8-1build2 \
      libfreetype-dev=2.14.2+dfsg-1 \
      libfreetype6=2.14.2+dfsg-1 \
      libfribidi-dev=1.0.16-5 \
      libfribidi0=1.0.16-5 \
      libgcc-15-dev=15.2.0-16ubuntu1 \
      libgcc-s1=16-20260322-1ubuntu1 \
      libgdbm-compat4t64=1.26-1build1 \
      libgdbm6t64=1.26-1build1 \
      libgdk-pixbuf-2.0-0=2.44.5+dfsg-4ubuntu1 \
      libgdk-pixbuf-2.0-dev=2.44.5+dfsg-4ubuntu1 \
      libgdk-pixbuf2.0-bin=2.44.5+dfsg-4ubuntu1 \
      libgdk-pixbuf2.0-common=2.44.5+dfsg-4ubuntu1 \
      libgio-2.0-dev=2.88.0-1 \
      libgio-2.0-dev-bin=2.88.0-1 \
      libgirepository-2.0-0=2.88.0-1 \
      libglib2.0-0t64=2.88.0-1 \
      libglib2.0-bin=2.88.0-1 \
      libglib2.0-data=2.88.0-1 \
      libglib2.0-dev=2.88.0-1 \
      libglib2.0-dev-bin=2.88.0-1 \
      libglycin-2-0=2.1.1+ds-0ubuntu1 \
      libglycin-2-dev=2.1.1+ds-0ubuntu1 \
      libgmp-dev=2:6.3.0+dfsg-5ubuntu2 \
      libgmp10=2:6.3.0+dfsg-5ubuntu2 \
      libgmpxx4ldbl=2:6.3.0+dfsg-5ubuntu2 \
      libgnutls-dane0t64=3.8.12-2ubuntu1 \
      libgnutls-openssl27t64=3.8.12-2ubuntu1 \
      libgnutls28-dev=3.8.12-2ubuntu1 \
      libgnutls30t64=3.8.12-2ubuntu1 \
      libgomp1=16-20260322-1ubuntu1 \
      libgprofng0=2.46-3ubuntu2 \
      libgraphite2-3=1.3.14-11ubuntu1 \
      libgraphite2-dev=1.3.14-11ubuntu1 \
      libgraphviz-dev=14.1.2-1ubuntu1 \
      libgs-common=10.06.0~dfsg-3ubuntu1 \
      libgs10=10.06.0~dfsg-3ubuntu1 \
      libgs10-common=10.06.0~dfsg-3ubuntu1 \
      libgssapi-krb5-2=1.22.1-2ubuntu4 \
      libgssrpc4t64=1.22.1-2ubuntu4 \
      libgvc-dev=14.1.2-1ubuntu1 \
      libgvc7=14.1.2-1ubuntu1 \
      libharfbuzz-cairo0=12.3.2-2 \
      libharfbuzz-dev=12.3.2-2 \
      libharfbuzz-gobject0=12.3.2-2 \
      libharfbuzz-icu0=12.3.2-2 \
      libharfbuzz-subset0=12.3.2-2 \
      libharfbuzz0b=12.3.2-2 \
      libheif-dev=1.21.2-3 \
      libheif-plugin-aomdec=1.21.2-3 \
      libheif1=1.21.2-3 \
      libhogweed6t64=3.10.2-1 \
      libhwasan0=16-20260322-1ubuntu1 \
      libhwy-dev=1.3.0-2 \
      libhwy1t64=1.3.0-2 \
      libice-dev=2:1.1.1-1build1 \
      libice6=2:1.1.1-1build1 \
      libicu-dev=78.2-2ubuntu1 \
      libicu78=78.2-2ubuntu1 \
      libidn12=1.43-2build1 \
      libidn2-0=2.3.8-4build1 \
      libidn2-dev=2.3.8-4build1 \
      libijs-0.35=0.35-16 \
      libimath-3-1-29t64=3.1.12-1ubuntu5 \
      libimath-dev=3.1.12-1ubuntu5 \
      libisl23=0.27-1build1 \
      libitm1=16-20260322-1ubuntu1 \
      libjansson4=2.14-2build4 \
      libjbig-dev=2.1-6.1ubuntu3 \
      libjbig0=2.1-6.1ubuntu3 \
      libjbig2dec0=0.20-1build4 \
      libjpeg-turbo8=2.1.5-4ubuntu4 \
      libjpeg-turbo8-dev=2.1.5-4ubuntu4 \
      libjpeg8=8c-2ubuntu12 \
      libjxl-dev=0.11.1-6ubuntu4 \
      libjxl0.11=0.11.1-6ubuntu4 \
      libk5crypto3=1.22.1-2ubuntu4 \
      libkadm5clnt-mit12=1.22.1-2ubuntu4 \
      libkadm5srv-mit12=1.22.1-2ubuntu4 \
      libkdb5-10t64=1.22.1-2ubuntu4 \
      libkeyutils1=1.6.3-6ubuntu3 \
      libkrb5-3=1.22.1-2ubuntu4 \
      libkrb5-dev=1.22.1-2ubuntu4 \
      libkrb5support0=1.22.1-2ubuntu4 \
      liblcms2-2=2.17-1 \
      liblcms2-dev=2.17-1 \
      libldap-common=2.6.10+dfsg-1ubuntu5 \
      libldap-dev=2.6.10+dfsg-1ubuntu5 \
      libldap2=2.6.10+dfsg-1ubuntu5 \
      liblerc-dev=4.0.0+ds-5ubuntu2 \
      liblerc4=4.0.0+ds-5ubuntu2 \
      liblqr-1-0=0.4.2-2.2 \
      liblqr-1-0-dev=0.4.2-2.2 \
      liblsan0=16-20260322-1ubuntu1 \
      libltdl7=2.5.4-9 \
      liblzma-dev=5.8.3-1 \
      liblzma5=5.8.3-1 \
      liblzo2-2=2.10-3build2 \
      libmagic-mgc=1:5.46-5build2 \
      libmagic1t64=1:5.46-5build2 \
      libmd0=1.1.0-2build4 \
      libmount-dev=2.41.3-3ubuntu2 \
      libmount1=2.41.3-3ubuntu2 \
      libmpc3=1.3.1-3 \
      libmpfr6=4.2.2-3 \
      libncursesw6=6.6+20251231-1 \
      libnettle8t64=3.10.2-1 \
      libnghttp2-14=1.68.0-2 \
      libnghttp2-dev=1.68.0-2 \
      libopenexr-3-1-30=3.1.13-2build1 \
      libopenexr-dev=3.1.13-2build1 \
      libopenjp2-7=2.5.4-1 \
      libopenjp2-7-dev=2.5.4-1 \
      libp11-kit-dev=0.26.2-2 \
      libp11-kit0=0.26.2-2 \
      libpam-modules=1.7.0-5ubuntu3 \
      libpam-modules-bin=1.7.0-5ubuntu3 \
      libpam-runtime=1.7.0-5ubuntu3 \
      libpam0g=1.7.0-5ubuntu3 \
      libpango-1.0-0=1.57.0-1 \
      libpango1.0-dev=1.57.0-1 \
      libpangocairo-1.0-0=1.57.0-1 \
      libpangoft2-1.0-0=1.57.0-1 \
      libpangoxft-1.0-0=1.57.0-1 \
      libpaper2=2.2.5-0.3maysync1 \
      libpathplan-dev=14.1.2-1ubuntu1 \
      libpathplan4=14.1.2-1ubuntu1 \
      libpcre2-16-0=10.46-1build1 \
      libpcre2-32-0=10.46-1build1 \
      libpcre2-8-0=10.46-1build1 \
      libpcre2-dev=10.46-1build1 \
      libpcre2-posix3=10.46-1build1 \
      libperl5.40=5.40.1-7build1 \
      libpixman-1-0=0.46.4-1 \
      libpixman-1-dev=0.46.4-1 \
      libpkgconf7=2.5.1-4 \
      libpng-dev=1.6.57-1 \
      libpng16-16t64=1.6.57-1 \
      libproc2-0=2:4.0.4-9ubuntu1 \
      libpsl-dev=0.21.2-1.1build2 \
      libpsl5t64=0.21.2-1.1build2 \
      libpython3-stdlib=3.14.3-0ubuntu2 \
      libpython3.14-minimal=3.14.4-1 \
      libpython3.14-stdlib=3.14.4-1 \
      libquadmath0=16-20260322-1ubuntu1 \
      libraqm-dev=0.10.4-1 \
      libraqm0=0.10.4-1 \
      libraw-dev=0.21.5b-1ubuntu1 \
      libraw23t64=0.21.5b-1ubuntu1 \
      libreadline8t64=8.3-4 \
      librsvg2-2=2.61.3+dfsg-3 \
      librsvg2-common=2.61.3+dfsg-3 \
      librsvg2-dev=2.61.3+dfsg-3 \
      librtmp-dev=2.4+20151223.gitfa8646d.1-3 \
      librtmp1=2.4+20151223.gitfa8646d.1-3 \
      libsasl2-2=2.1.28+dfsg1-9ubuntu3 \
      libsasl2-modules-db=2.1.28+dfsg1-9ubuntu3 \
      libseccomp-dev=2.6.0-2ubuntu5 \
      libseccomp2=2.6.0-2ubuntu5 \
      libselinux-dev=3.9-4build1 \
      libselinux1=3.9-4build1 \
      libsemanage-common=3.9-1build1 \
      libsemanage2=3.9-1build1 \
      libsepol-dev=3.9-2 \
      libsepol2=3.9-2 \
      libsframe3=2.46-3ubuntu2 \
      libsharpyuv-dev=1.5.0-0.1build1 \
      libsharpyuv0=1.5.0-0.1build1 \
      libsm-dev=2:1.2.6-1build1 \
      libsm6=2:1.2.6-1build1 \
      libsmartcols1=2.41.3-3ubuntu2 \
      libsqlite3-0=3.46.1-9 \
      libsqlite3-dev=3.46.1-9 \
      libss2=1.47.2-3ubuntu4 \
      libssh2-1-dev=1.11.1-1build2 \
      libssh2-1t64=1.11.1-1build2 \
      libssl-dev=3.5.5-1ubuntu3 \
      libssl3t64=3.5.5-1ubuntu3 \
      libstdc++-15-dev=15.2.0-16ubuntu1 \
      libstdc++6=16-20260322-1ubuntu1 \
      libsysprof-capture-4-dev=50.0-1 \
      libtasn1-6=4.21.0-2 \
      libtasn1-6-dev=4.21.0-2 \
      libtext-charwidth-perl=0.04-11build4 \
      libtext-wrapi18n-perl=0.06-10 \
      libthai-data=0.1.30-1 \
      libthai-dev=0.1.30-1 \
      libthai0=0.1.30-1 \
      libtiff-dev=4.7.0-3ubuntu4 \
      libtiff6=4.7.0-3ubuntu4 \
      libtiffxx6=4.7.0-3ubuntu4 \
      libtinfo6=6.6+20251231-1 \
      libtool=2.5.4-9 \
      libtsan2=16-20260322-1ubuntu1 \
      libubsan1=16-20260322-1ubuntu1 \
      libunbound8=1.24.2-1ubuntu2 \
      libunistring5=1.3-2build1 \
      libuuid1=2.41.3-3ubuntu2 \
      libwebp-dev=1.5.0-0.1build1 \
      libwebp7=1.5.0-0.1build1 \
      libwebpdecoder3=1.5.0-0.1build1 \
      libwebpdemux2=1.5.0-0.1build1 \
      libwebpmux3=1.5.0-0.1build1 \
      libx11-6=2:1.8.13-1 \
      libx11-data=2:1.8.13-1 \
      libx11-dev=2:1.8.13-1 \
      libxau-dev=1:1.0.11-1build2 \
      libxau6=1:1.0.11-1build2 \
      libxcb-render0=1.17.0-2ubuntu1 \
      libxcb-render0-dev=1.17.0-2ubuntu1 \
      libxcb-shm0=1.17.0-2ubuntu1 \
      libxcb-shm0-dev=1.17.0-2ubuntu1 \
      libxcb1=1.17.0-2ubuntu1 \
      libxcb1-dev=1.17.0-2ubuntu1 \
      libxdmcp-dev=1:1.1.5-2 \
      libxdmcp6=1:1.1.5-2 \
      libxdot4=14.1.2-1ubuntu1 \
      libxext-dev=2:1.3.4-1build3 \
      libxext6=2:1.3.4-1build3 \
      libxft-dev=2.3.6-1build2 \
      libxft2=2.3.6-1build2 \
      libxml2-16=2.15.2+dfsg-0.1 \
      libxml2-dev=2.15.2+dfsg-0.1 \
      libxrender-dev=1:0.9.12-1build1 \
      libxrender1=1:0.9.12-1build1 \
      libxt6t64=1:1.2.1-1.3build1 \
      libzip-dev=1.11.4-2 \
      libzip5=1.11.4-2 \
      libzstd-dev=1.5.7+dfsg-3 \
      libzstd1=1.5.7+dfsg-3 \
      linux-libc-dev=7.0.0-14.14 \
      login=1:4.16.0-2+really2.41.3-3ubuntu2 \
      login.defs=1:4.17.4-2ubuntu3 \
      logsave=1.47.2-3ubuntu4 \
      m4=1.4.21-1 \
      make=4.4.1-3 \
      mawk=1.3.4.20260129-1 \
      media-types=14.0.0build1 \
      mount=2.41.3-3ubuntu2 \
      native-architecture=0.2.6build1 \
      netbase=6.5build1 \
      nettle-dev=3.10.2-1 \
      openssl=3.5.5-1ubuntu3 \
      openssl-provider-legacy=3.5.5-1ubuntu3 \
      pango1.0-tools=1.57.0-1 \
      passwd=1:4.17.4-2ubuntu3 \
      perl=5.40.1-7build1 \
      perl-base=5.40.1-7build1 \
      perl-modules-5.40=5.40.1-7build1 \
      pkgconf=2.5.1-4 \
      pkgconf-bin=2.5.1-4 \
      poppler-data=0.4.12-1build1 \
      procps=2:4.0.4-9ubuntu1 \
      python3=3.14.3-0ubuntu2 \
      python3-minimal=3.14.3-0ubuntu2 \
      python3-packaging=26.0-1 \
      python3.14=3.14.4-1 \
      python3.14-minimal=3.14.4-1 \
      readline-common=8.3-4 \
      rpcsvc-proto=1.4.3-1build1 \
      sed=4.9-2build3 \
      sensible-utils=0.0.26build1 \
      sgml-base=1.31+nmu1build1 \
      shared-mime-info=2.4-5build3 \
      sysvinit-utils=3.15-5ubuntu1 \
      tar=1.35+dfsg-4 \
      tex-common=6.20 \
      tzdata=2026a-3ubuntu1 \
      ucf=3.0052ubuntu1 \
      util-linux=2.41.3-3ubuntu2 \
      uuid-dev=2.41.3-3ubuntu2 \
      x11-common=1:7.7+26ubuntu1 \
      x11proto-dev=2025.1-1 \
      xfonts-encodings=1:1.0.5-0ubuntu3 \
      xfonts-utils=1:7.7+7build1 \
      xorg-sgml-doctools=1:1.11-1.1build1 \
      xtrans-dev=1.6.0-1build1 \
      xz-utils=5.8.3-1 \
      zip=3.0-15ubuntu3 \
      zipcmp=1.11.4-2 \
      zipmerge=1.11.4-2 \
      ziptool=1.11.4-2 \
      zlib1g=1:1.3.dfsg+really1.3.1-1ubuntu3 \
      zlib1g-dev=1:1.3.dfsg+really1.3.1-1ubuntu3 \
 && printf '%s\n' \
      '0014788fec9bda1a4931e71a75523ba4055eb1a626582f445a2674528a32dbc7  libnghttp2-dev_1.68.0-2_amd64.deb' \
      '0068e6a881ab327aff6c0f57357de7f397cb43302a39b10015123c1914f14d2e  libgnutls30t64_3.8.12-2ubuntu1_amd64.deb' \
      '01daf029ba48bc9f4722b505a19918fafd0a70516b516b836a991ae5e37aec9a  libgdk-pixbuf-2.0-dev_2.44.5+dfsg-4ubuntu1_amd64.deb' \
      '025984be5dc70b32e02c8a668fdcceba674173bbda4a3e7ff93fac800dcdd122  debconf_1.5.92_all.deb' \
      '02ea5de2ab6ddba978606ad58647bf6371ea68c0ed63aa5d6d0d3b8c1fe77ea3  libisl23_0.27-1build1_amd64.deb' \
      '040a38c394002ffcea3f63bebb50b9edf474846341a22f496df943140ff2ca44  libopenexr-3-1-30_3.1.13-2build1_amd64.deb' \
      '05213cc9919e32e261479ec3a5fdf561da77f06d137046dd0d8b622ea3f0ea79  libwebpdemux2_1.5.0-0.1build1_amd64.deb' \
      '05541ea1edb19e54bea297a21a9c33d0b99ca2cfe2e86d4a67335e6640667cfc  libsframe3_2.46-3ubuntu2_amd64.deb' \
      '05a64873a18fb10d52ba2c8ee1fd0a605a974d75264d824ef2771c799f49ea63  cpp_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '05c9ab6be49c5177b366b21fc1b96e042d69e2c119de898d539e55a3a778f8f7  openssl-provider-legacy_3.5.5-1ubuntu3_amd64.deb' \
      '0662549ee8b9d4fc84c60d7a3881a04b5e4e1e07947e11cdc75b34f338e4a499  libgnutls-dane0t64_3.8.12-2ubuntu1_amd64.deb' \
      '06636633e9ac548395c6d5a9b9240dd1fdf39140f7bcc94431b9dcc8672b6387  libtiff-dev_4.7.0-3ubuntu4_amd64.deb' \
      '069e64705e4a5721a223b4d22643bbaeaa63a6efbb56ebd3d7c4a31c4a26fa1c  libxcb1_1.17.0-2ubuntu1_amd64.deb' \
      '06dc3b12e940079ba59da9877995f05ba01130739375563e910b94101760e000  libpng-dev_1.6.57-1_amd64.deb' \
      '0742e9d6a8f39f925a4f760512f1227bae3d7396208205b576a9bac9ca1c4b6e  librsvg2-common_2.61.3+dfsg-3_amd64.deb' \
      '0752eddff4c494d682f433cac2f1d25196f0a405eb8c6b0b10ec46432f6fec71  libgdbm6t64_1.26-1build1_amd64.deb' \
      '07672ce1f4d187e005ea0cc35d03e515ba056f3d3e7a9a25d3ef386e184da8c5  libjpeg-turbo8_2.1.5-4ubuntu4_amd64.deb' \
      '079f2a9cb6215753bcc13bfea01a136fd07376fb9f8c3233efc712df40e584bd  libp11-kit-dev_0.26.2-2_amd64.deb' \
      '07bd53c587140613b3d551bdbd4a15a37002c1fe971962ab49e2c2c896cf7dda  libgmpxx4ldbl_2%3a6.3.0+dfsg-5ubuntu2_amd64.deb' \
      '08d28bd0e1402f45c1e7c9b28cc65ec55442876217c9f553e8836c0622a71509  libss2_1.47.2-3ubuntu4_amd64.deb' \
      '090bb705b6d49213b288f19d78be78a55a1b72843efb12eae73ab5cca0f54b8d  bubblewrap_0.11.1-1_amd64.deb' \
      '09668f05e1a860672d94f31a5ae025d2b41269ff6cc5479554825758ee9dcf3a  libsemanage-common_3.9-1build1_all.deb' \
      '0a846cf63522d9c1f28d31bdd53e35e223d590a0971bb6927b3ee5092934ce9d  libwebp7_1.5.0-0.1build1_amd64.deb' \
      '0c0734376290e2fa302a5830dfc8551efe9c87606d7cc24a1686b3ae970c11c8  libsharpyuv-dev_1.5.0-0.1build1_amd64.deb' \
      '0c58fa90fcb38c1bcc0dbce47b105c60c990128e0220b087f4513d82499d404e  libext2fs2t64_1.47.2-3ubuntu4_amd64.deb' \
      '0ddc3bded4b40436326b03096702f228d46a65b0deae27c1d5c0e3bdca162303  libfftw3-long3_3.3.10-2fakesync1build3_amd64.deb' \
      '0df82e6018f7f1f9a7aeb11e2813f465518a728e8da668b88bef72d42989beb6  libwebp-dev_1.5.0-0.1build1_amd64.deb' \
      '0e8652c2f0ff6ed0ca711bd085e97c492c3d0ae6605dfa8fc543d415720ddfed  libgs10_10.06.0~dfsg-3ubuntu1_amd64.deb' \
      '0f57948b8c1d4f369f14dc3897d4985227020d57b798a7ddd1b9acb2a8ea430d  libsqlite3-dev_3.46.1-9_amd64.deb' \
      '11b9b2ce6702d86dd3dea60e08bd15255d7fd9545431a9e555eec47770404de0  libsasl2-2_2.1.28+dfsg1-9ubuntu3_amd64.deb' \
      '1312f58a50fac42b088766dbf4dd3c73137c3fbfb875eda130a68ada382f875c  libharfbuzz-gobject0_12.3.2-2_amd64.deb' \
      '1376a5e49c8dc2ba938fadc15fce40dd01c7fbf1adf2d506a2a7cf7148e347c8  libbinutils_2.46-3ubuntu2_amd64.deb' \
      '13bb794692dbf0f7f5cdaf5df65ef822d22c8499bf1d031dd7eb9c6b0746378e  libpam-modules_1.7.0-5ubuntu3_amd64.deb' \
      '1403d44d2c2d3eba6a7a8aea97fab0bac2e89e144a3bf600adfdd3ecdc3d9394  libjpeg8_8c-2ubuntu12_amd64.deb' \
      '14bf36d574df2cacf2e50fa8c1f28b4b6b574b63e9561924cc942e4c9186e57e  linux-libc-dev_7.0.0-14.14_amd64.deb' \
      '150603a0792b1d22aa0bde0a26c27b413018c799284003e4b43cba587a5b3a18  libcap2_1%3a2.75-10ubuntu2_amd64.deb' \
      '1649aa71c45b047feda5b9ca303c94799bdba5befa5c9de9735cbfc59c3ef93f  cpp-15-x86-64-linux-gnu_15.2.0-16ubuntu1_amd64.deb' \
      '167414af3004dbdb0ec9099ce9dd65141f9257a7622eebcefc3875fc9499ab1f  libpcre2-posix3_10.46-1build1_amd64.deb' \
      '180b6ea0b9c07d4fd2ede79e29ee8eca830cd9384f856507e28dc24d1d3ae514  libcom-err2_1.47.2-3ubuntu4_amd64.deb' \
      '1890e37e38fd64bc10630e508f4a013a76bddbe05be2ed89e68df28463712b55  m4_1.4.21-1_amd64.deb' \
      '18b35148f64d0bb17b5c34efa6bdeefa4df9ca122ba12130f7245bccd65a950a  cpp-x86-64-linux-gnu_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '18cfdce1831fb38878a9987cacd02b1a69ea7bda545f6e8eb737742defcd24b5  libpam-modules-bin_1.7.0-5ubuntu3_amd64.deb' \
      '195ca7b0ca6c91c4b4b9e17baf98b98143e3a14a0571f1613f04b318b9799510  libattr1_1%3a2.5.2-4_amd64.deb' \
      '1a443abf03a5af97f4493405e22eba52fd6935a8b0583ac32fb88b3727563e53  automake_1%3a1.18.1-3build1_all.deb' \
      '1adaaf191b33e95bc172e0cae09e4a246e22fb7dcf46a34e3e9ae66f8efbe994  diffutils_1%3a3.12-1_amd64.deb' \
      '1ae62705714f660ecdfd70273fce5b226b6cb7b9fe53776531799093edc99774  libpsl5t64_0.21.2-1.1build2_amd64.deb' \
      '1b11365293bf98d107f85f8a725636c203d08b6e7b93a4268492758ef18217f2  zipmerge_1.11.4-2_amd64.deb' \
      '1ba5a9190119370912ec5955c8129cdf2780a098ed6c80e9ecca05cc515bd039  libdatrie1_0.2.14-1_amd64.deb' \
      '1babf5e00ac77a6399ae51c08517d8b1d55d33f48f651565707b805a2ff83c6f  libidn12_1.43-2build1_amd64.deb' \
      '1c8c808ab24ff3018ac886e3f311edee0f2d4d97d12d3908be52343e89807046  libhogweed6t64_3.10.2-1_amd64.deb' \
      '1d0610635e1fe757c8df0ec2c2cef511203c7e7bf81bbff332031c8bf87b1847  xfonts-encodings_1%3a1.0.5-0ubuntu3_all.deb' \
      '1d48661d59bb164fc27e88bb8e6a8dab0cdfdbf35ea5d2bbf3ebffe849a38822  libcairo-gobject2_1.18.4-3_amd64.deb' \
      '1d6f5ed9563208a63357e089ed59471cdfa77d8b6f55590df56567dae5123522  libglib2.0-dev_2.88.0-1_amd64.deb' \
      '1dc986ac3cf112384919d1a339a952e8a86bede9890a4489c016fdc266a036ca  libjansson4_2.14-2build4_amd64.deb' \
      '1de7b83844537091315210afb466ff2cd022874db5a6a785ce06b41bd3507eb3  libsasl2-modules-db_2.1.28+dfsg1-9ubuntu3_amd64.deb' \
      '1f40a027bc0b31bec572baadb8d9dff7477e4fe00fa389a33a2e5f78607301b6  perl-modules-5.40_5.40.1-7build1_all.deb' \
      '1f47dbb4b688665621f5846043ab20ff00ad0859bedfea93d019a0b66978331d  libtasn1-6-dev_4.21.0-2_amd64.deb' \
      '1f75dadc130553848448621d10fcc7cf750e43fece5e6250bef3e34c0cb31653  libjpeg-turbo8-dev_2.1.5-4ubuntu4_amd64.deb' \
      '1fab0e125d793da45d91b346c334c496776d69709a7ea78c3b34d5db6db69eab  libfontenc1_1%3a1.1.8-1build2_amd64.deb' \
      '1ff88ad587f9e52e9f333ab00ae0babea93ac5222fc6909039c4190affe1d574  python3_3.14.3-0ubuntu2_amd64.deb' \
      '203dd2049aebc6e7d674f79e5f377263a1907e156469b496378047a20ecf3e54  libpcre2-dev_10.46-1build1_amd64.deb' \
      '21cf3afb6ca2d83dd959f4a6550720b44f89a32633f62cdac3e63b622e3966f6  libxrender-dev_1%3a0.9.12-1build1_amd64.deb' \
      '21f699abaaa7624b0206573f69bf4f7a902d92863f2c9dfba497662c5713456b  libdebconfclient0_0.280ubuntu1_amd64.deb' \
      '226c75127e46de2bbd8a329ac7e55781ede395ab8a9be0f269250b24c81b9c36  base-passwd_3.6.8_amd64.deb' \
      '229301edd46bf07c142eaa87aae3a9d69e6e1f4b57f1d78a7cdbd267fa032182  passwd_1%3a4.17.4-2ubuntu3_amd64.deb' \
      '23e5845ebf1cde73cc4912b9e0f13996907b56c934262ad527f3e2a7ef4e1425  libmount-dev_2.41.3-3ubuntu2_amd64.deb' \
      '241347f05c984b5fdf71180d0cfe86f83a8249ceda218329cb3119f0a7ad30e7  libbz2-dev_1.0.8-6build2_amd64.deb' \
      '2439c70d04fa6148b1bf3ae2b77d999d8c0906fbd540c60a2bc0463a43b7a9b3  sysvinit-utils_3.15-5ubuntu1_amd64.deb' \
      '243b02ca4ce4008daad2cda307b21e1f39cda04b2e46a087ea6fc41592c2690a  python3.14_3.14.4-1_amd64.deb' \
      '2476d552009724d9b027236fcd2e4540a46f419d9d8b881f1d92edf10d6fcc13  libgdk-pixbuf2.0-common_2.44.5+dfsg-4ubuntu1_all.deb' \
      '260b3333e9f714252593b83fb31d2571097b64d337d0d7100aae7349029821fc  libreadline8t64_8.3-4_amd64.deb' \
      '27bd62095230d0cd3a2faf5bd1b64b1b3ca2f799980245e2aabd8685d151d88e  libpango1.0-dev_1.57.0-1_amd64.deb' \
      '281b3188840a7abdca85a02eb2609b0efad852e8994b3804a0e4227ec4ec3f90  gcc-16-base_16-20260322-1ubuntu1_amd64.deb' \
      '28da225c111d3ce9d230209cca24db46ec645f631f593f188bef718d8a1e4711  gcc-15_15.2.0-16ubuntu1_amd64.deb' \
      '29051d37d010a7a0e3b5648f73f30d35eb1e313061137c88f3a2c2078925a36d  liblerc4_4.0.0+ds-5ubuntu2_amd64.deb' \
      '2b94910793dddd6cc6cc689bea65c526e3c3e3dfd2125f4464c239fc6e5856d4  glycin-loaders_2.1.1+ds-0ubuntu1_amd64.deb' \
      '2bdd10dd88c99523a62bfcc2b71b59fdf93ee396e8baf617c76fc3ec38f39bde  libxcb-render0_1.17.0-2ubuntu1_amd64.deb' \
      '2be84461c2f47fd7ce2cfea2e35d775d0e30582879bf1c0e80a1c22f92a2cdac  g++_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '2be9a2694b5d073e96e8d034ba358e0f6d4bf541740be25938a814fcd35b6a45  cpio_2.15+dfsg-2.1_amd64.deb' \
      '2fb4d81c14fdf34251639ae82f5181f9f98480ea16125d535571ac1be9db3065  libgcc-s1_16-20260322-1ubuntu1_amd64.deb' \
      '300abd658047ee4aeeef8e120c1950d1c253c0a4c27acf9999e232393a4fb385  libselinux-dev_3.9-4build1_amd64.deb' \
      '304cc61f61b94399453db02e1032d9f74a0bd737307acb4ed847f8da9406b8c1  fontconfig-config_2.17.1-3ubuntu1_amd64.deb' \
      '3059f000ecd4c681a24effba374844bd674b45dc744f4d971afcecba9c7dfea2  libgvc7_14.1.2-1ubuntu1_amd64.deb' \
      '309f30a8ea77e0264a3c8b66811188f5b788fe87b33be3cafd97c8f221235591  libpango-1.0-0_1.57.0-1_amd64.deb' \
      '30a71a4e787afa88617b8f9239fd4ddbccfddb54dc63fef0b1687cecc60e510c  ghostscript_10.06.0~dfsg-3ubuntu1_amd64.deb' \
      '3264ec3ed617abec65c55f2e165cf78f8c9dd006859faf0d863a8bc6095a67fd  libmagic-mgc_1%3a5.46-5build2_amd64.deb' \
      '32fa5bde1891f46fd4f422e466c863fb78e834b634e1aa08211c8eea68870af5  libgcc-15-dev_15.2.0-16ubuntu1_amd64.deb' \
      '3311a37b33a25fe28e40cae480af72124431353656b5a1a698350938efc47207  libdjvulibre-dev_3.5.29-1_amd64.deb' \
      '3331efa0bfbf0caeed828beddb179e32719f744891359bd28beb489f8f7a9fbd  login.defs_1%3a4.17.4-2ubuntu3_all.deb' \
      '335d24663b21e07b3850565d70d173399cf8b9bb59ad3be17bd5c98e9fadce0a  libicu-dev_78.2-2ubuntu1_amd64.deb' \
      '33fa4609c725abe2a8526b9e622af52c71265436af038f836fd09765c803c964  libzip-dev_1.11.4-2_amd64.deb' \
      '34365d611ccf1f717f90a92fbe52ed96ae1829ab9be363c68a83563322797f8f  libzstd1_1.5.7+dfsg-3_amd64.deb' \
      '345fa75fcec8b562e2c6a4a5cd61187e7b825c8379fadb7f3f60d64d73ab1b72  libthai-data_0.1.30-1_all.deb' \
      '34b1757ce619720541c7e1e8d8f3aa506cb327731374e284ffb6ec872a2c566f  libctf0_2.46-3ubuntu2_amd64.deb' \
      '353f622f6432a3d65bedd3c23e0af98c2c438650b497b355772a56a05ebf7dd0  libpkgconf7_2.5.1-4_amd64.deb' \
      '35468e313e59a20d9388b554a6d02634c65a17596d928723c228a17f1ce486e0  gir1.2-rsvg-2.0_2.61.3+dfsg-3_amd64.deb' \
      '3552dd7d4b8c6bf1b25dba129290fc46b6421197587e2e211aa0dbe5f8beea54  libpython3.14-minimal_3.14.4-1_amd64.deb' \
      '37ef83a264896236a84b3b170b655b2c6929d460afe4fb1bd234149473ad2098  libzip5_1.11.4-2_amd64.deb' \
      '387910c6d79c39c47d83ca729b84c0d30c674a340e3b290ec7b6df3288c19f9a  libbz2-1.0_1.0.8-6build2_amd64.deb' \
      '38ad8500817a9159db210fecfb8c50fa82d7a8829730fcdf8ae60e3523676d41  liblzma5_5.8.3-1_amd64.deb' \
      '3abb79b2eb8514f81c867dbed0b37d85efc86c51c4585c378b49b70da8402985  zipcmp_1.11.4-2_amd64.deb' \
      '3b73ea5df272886f6bca236798eea769b8bc2b99337a55a0ae5f779b310a918c  libpython3.14-stdlib_3.14.4-1_amd64.deb' \
      '3c846f001d87b16e5038a3919ca975276808a2db17459308a9d0f965c1cddac5  binutils-common_2.46-3ubuntu2_amd64.deb' \
      '3ce3aea44b2ec00780c48b1b8e1f7e672166ec3ccac14b0eae8890e55983061e  libselinux1_3.9-4build1_amd64.deb' \
      '3e116766f1a7b149994d4745556023d993d26401223d1595520a991d4ba737fb  libpcre2-8-0_10.46-1build1_amd64.deb' \
      '3e8d20b877d0729aef0e990c1c382d42d3095261f941492a0458407d80020dc1  libgvc-dev_14.1.2-1ubuntu1_amd64.deb' \
      '3f8edc884ebb8c55120cb0535fb4e1029651d97fd380936ec5211bb4c926d809  perl-base_5.40.1-7build1_amd64.deb' \
      '3fb1a0d6e58a8fa9cc5481ec476c01038325b146319ed9fc599d48b3b1e1067d  libexpat1-dev_2.7.4-1_amd64.deb' \
      '3fff865e0ac12c9a1e1da0a2ba42a9a2f3daa909b51ec859a3a6815f3d8d24ab  libbrotli-dev_1.2.0-3build1_amd64.deb' \
      '40ee517cffd3730405be6ae30826533bec0ddf8773bb7ac2cccd22a57acafc25  libdeflate0_1.23-2ubuntu1_amd64.deb' \
      '41f3cecf36e5e82fc7d86f93611306b49c5ff4ab947cd574b0a8787faedf4fed  util-linux_2.41.3-3ubuntu2_amd64.deb' \
      '420e777fef436f397a85ddedde53fbb44f92c7ca8e87d581f9d86573859e1aa4  libquadmath0_16-20260322-1ubuntu1_amd64.deb' \
      '42354d322fda598511b62288123e8b4b6daf6b7bbb268d68e8e7f88efa498305  ucf_3.0052ubuntu1_all.deb' \
      '42705a701a98d84c203c6f96f08c6fd6a29a1ef978683e1ffbf0e27535b20ddb  libtinfo6_6.6+20251231-1_amd64.deb' \
      '42b813715907215cbd85df690aabc0777e77b9f73cd8868cc3d4b02ffa1f82d3  icu-devtools_78.2-2ubuntu1_amd64.deb' \
      '43083dd9f4895b125eb01a4575c8b1decb4ea3ec0fb576bc1b4c53ecd1bb2fe2  libice-dev_2%3a1.1.1-1build1_amd64.deb' \
      '434394dc6703f8e195c19764bd03aa55a0a9986749285fd7abe0a0e4ab086cfc  autotools-dev_20240727.1build1_all.deb' \
      '45d8edc3e6775179bee9ecb0211727e3e8d53ee3caf4ddb2e1310ac28080053d  g++-x86-64-linux-gnu_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '465cb25b468c5f6e883f3ae46c044506e14cdd1aed539a9cc19ce1be8a31d517  logsave_1.47.2-3ubuntu4_amd64.deb' \
      '471b02803d2ff240a28d03059ac9bd676b1f9e25bfd84b8feef95171bbf1da90  procps_2%3a4.0.4-9ubuntu1_amd64.deb' \
      '4755b21ef0f3c04a9b7544d31341e8fbf3e835817e7b65e5f1b7e17b855c3c43  liblzma-dev_5.8.3-1_amd64.deb' \
      '47d00e206617cc92aa319b6b0430f77460826bd7f15c1b3d5171e1646545f9f2  libproc2-0_2%3a4.0.4-9ubuntu1_amd64.deb' \
      '47fb50e96401a46c06d5122cd04cc42316f65530b9f868d2d450576a379d5d34  libfribidi0_1.0.16-5_amd64.deb' \
      '484ac5fd30a19bfade8db336fe70f3c046beccd1c9a9ac327fcd89d29dd5a125  libcc1-0_16-20260322-1ubuntu1_amd64.deb' \
      '49c68d09ceaaf5198966cf1e077ae9bf23d345189cb90e564bcd6594fd83a9fd  init-system-helpers_1.69_all.deb' \
      '4a7423124bbd459c0aa38b7389ec7802fa6899654767a95fc27de70967fedd48  libffi8_3.5.2-4_amd64.deb' \
      '4aba1f758114185fbaa798acfd4570492a5ce0ff906d36998544a68b361c785f  libldap-dev_2.6.10+dfsg-1ubuntu5_amd64.deb' \
      '4e066f8382f775d6600eee715add8fdc8da5ea8f0cf7b0f715aba38c8d57d64f  tar_1.35+dfsg-4_amd64.deb' \
      '4e2c0a8aa97dafd923f00d77ca017d14f16ab79d3b1120892c8215a0b5fb7892  libsharpyuv0_1.5.0-0.1build1_amd64.deb' \
      '4f4b3f31d70a4038f54626c2eeacd18d9495936ee4bc6fafdbdd59098a3ab15f  libpathplan-dev_14.1.2-1ubuntu1_amd64.deb' \
      '5135ba4f61cc3f71f73d3992b68b2fb08eedac7269a7070ce16d44671f143c04  libharfbuzz-subset0_12.3.2-2_amd64.deb' \
      '516ad272f711e3c4550307ff6d6e1cbc828e3f4744471ffa0389430739197c81  libcairo-script-interpreter2_1.18.4-3_amd64.deb' \
      '525ab7b5ad6529ea35aa09308ddd1fd2325c85ad70e7483ba66b526d8ee9f7a7  libcairo2_1.18.4-3_amd64.deb' \
      '526ae12ddc13b3c7a9b582e44f43d376aa248e896b2ecf21be1b0c3dc36bfd18  libimath-3-1-29t64_3.1.12-1ubuntu5_amd64.deb' \
      '52cc67a0a52735fe72b1d02ccf47b8b0b7533971a541b0ac289ad91bec548d8d  libgnutls-openssl27t64_3.8.12-2ubuntu1_amd64.deb' \
      '52df349d6b4724ccbb309294d055a2e419ad41d77a02e5072a2a16d0febede3b  libblkid-dev_2.41.3-3ubuntu2_amd64.deb' \
      '53cdc5a963bbdda938f8996496a5e78bcf484e6e41a2ef2c0f8cf566808f71f5  readline-common_8.3-4_all.deb' \
      '54300431ee2e613382946baddc01ecd6135bb9d086ec914d0a727b8c14ce497b  libdjvulibre-text_3.5.29-1_all.deb' \
      '545e2b60f3a2ceefe6f1b99c98b229806aafde57fdcae6b67030b7a09b808cc2  glycin-thumbnailers_2.1.1+ds-0ubuntu1_amd64.deb' \
      '546d6b0c2b2f5c61494ee5d11aa1b49476213af27a66edd9e05bb3ef00940557  findutils_4.10.0-3build2_amd64.deb' \
      '55089bcbe8f6213d500900769f5161e35fb9e4147cf472b469a37e1d1e96a022  libtext-charwidth-perl_0.04-11build4_amd64.deb' \
      '55a274db32d4824a1f1a48c42e959fe4293a4e4b545d400d89949cfabe160cc3  libpixman-1-0_0.46.4-1_amd64.deb' \
      '55a7100aa12d940c41e0735212122cc835192bce385e7bbfe14b234759aad51c  libxau-dev_1%3a1.0.11-1build2_amd64.deb' \
      '563091a9b615a5a59951c2cc4478163d099df366a051113e8ce5bb2baab7f0c8  dash_0.5.12-12ubuntu3_amd64.deb' \
      '5663c9bb5329be367a8809332514943e8b551b90b2b6351142d58dcde332ad24  libfribidi-dev_1.0.16-5_amd64.deb' \
      '57ab343c3dd28ce7101dc4e23de4e9d5bd3e58c6cb0ecd5ba0c42a877fc8868a  libcrypt1_1%3a4.5.1-1_amd64.deb' \
      '58a8f3f358a96d0039671c697a8241781fc95f70593aafef78b7d09625305d13  gir1.2-gdkpixbuf-2.0_2.44.5+dfsg-4ubuntu1_amd64.deb' \
      '58de54e02b08378ff727c22bab862c9925f833e0d069aa1ca3c754bc6ab3416d  libhwy-dev_1.3.0-2_amd64.deb' \
      '5924ddbd18786bd8ab7062879db324e975d056420b2e7b84826f59d63efac559  libavahi-client3_0.8-18ubuntu1_amd64.deb' \
      '59c74951324ead0ff77ab945d561feb1b21bc189b793600b8e2b7cf4d39b1ee5  libtasn1-6_4.21.0-2_amd64.deb' \
      '5a1a4cd407a868e766626f551646b00880fc1534db5e6d47208310a17252f306  gettext-base_0.23.2-1_amd64.deb' \
      '5a302d705d562fb7e150415b00651c00fed58b633faadff0b332eac1b73fadb3  gcc-15-base_15.2.0-16ubuntu1_amd64.deb' \
      '5a8cddf80d9f5aeee1f39315158cfcc0f3e2c7573f9d6236fc6b85537400a937  xz-utils_5.8.3-1_amd64.deb' \
      '5acad718e7fe39a7407d87402112a3bac97948723e5ea058c5996e32e8ceeb1e  libkadm5srv-mit12_1.22.1-2ubuntu4_amd64.deb' \
      '5b3146cd9d380e4725fc5b5e54795ae1f72d165d93e68ce29076b69762661fd4  libtool_2.5.4-9_all.deb' \
      '5ca038ae110ddf65e190b9fe88822592abd45cecba5001f3e4ce7692ca1f31be  libctf-nobfd0_2.46-3ubuntu2_amd64.deb' \
      '5cdece41b30145cb87cf6d2e0a1de812269d3c80b066e109b6201f75abfe7243  libcdt6_14.1.2-1ubuntu1_amd64.deb' \
      '5de129b859b79eab3a273c77dcc450a521fd28cff3920b679ad6ad99fcf6fbb6  libxext-dev_2%3a1.3.4-1build3_amd64.deb' \
      '5f0bedb659736b00c2d279b504317f5c2a9fea88983a5c211ee1142d17581c2b  libopenexr-dev_3.1.13-2build1_amd64.deb' \
      '5f87d9f0ff7189e5dbf7bedd1ef6c09ea81747bc68dd5263ea811b471f23ee65  fontconfig_2.17.1-3ubuntu1_amd64.deb' \
      '5fe36591ab13d2bd63197cfe6b06e3a9b1fb2bf97b3be67883bb3807fcc8fc32  openssl_3.5.5-1ubuntu3_amd64.deb' \
      '601b9f92a04ea9ff7de6f60f60c34f2e2743f9c478125ac9e413f29a1fa728d9  zlib1g-dev_1%3a1.3.dfsg+really1.3.1-1ubuntu3_amd64.deb' \
      '60b2f01e8124318e2a11049b82c764fd4c05c21adba11312e93ab116d6594f1e  libxrender1_1%3a0.9.12-1build1_amd64.deb' \
      '60b7a5982b477e10b9f11e2278289135f79e9dc75a312575778b21a0a631bea5  x11-common_1%3a7.7+26ubuntu1_all.deb' \
      '62019928a6baeaba8d12d2d4cb7c1e4c9a9550a1eb4541b8de0cacfeae1d09e3  libbsd0_0.12.2-2build2_amd64.deb' \
      '62524c67075889b68fa441851604ee7f801f89d0b9a20bc9db55f52561a7cb3b  libpsl-dev_0.21.2-1.1build2_amd64.deb' \
      '62a09e8a10b1b7704dace298fd2a0e65e414890297497d5b4ac1a96891b3dd6f  libidn2-dev_2.3.8-4build1_amd64.deb' \
      '63ece6297e34148e2cad22968059b7ac4e631b0ce2aaffa8424774fa2e02dacf  libssh2-1t64_1.11.1-1build2_amd64.deb' \
      '64e76233a9f5f346f6f4ed90adf98937670b107e08a37ef208adcd28d93b5fd9  mount_2.41.3-3ubuntu2_amd64.deb' \
      '6640ca09cf01f893c02b525044843423ff91a3f43fd7f835ad930f73990108a8  libcairo2-dev_1.18.4-3_amd64.deb' \
      '67292d559b11f0fc8d63d97a352e3aa3710744fee0f478fc6a695723ca64eb6b  libkdb5-10t64_1.22.1-2ubuntu4_amd64.deb' \
      '67bea9f8bbe05d3b4a827d447a9bb2849a7195c4ddecd83644cd57aa7871d594  libtiff6_4.7.0-3ubuntu4_amd64.deb' \
      '6899c78615e681af21b88f00ac6b5b3966319093bc0bb7073ab1ed2e80192cf5  libgraphite2-3_1.3.14-11ubuntu1_amd64.deb' \
      '6a4f5c6f4bc1a7f67f35163fed1fc9ecc9d8a448d7223dd41ef019860a9c803e  tex-common_6.20_all.deb' \
      '6a5d8c40c25df7d300ca2359587e2a0726f7df9459c87d267ab4c6aa4a0c10fb  libglib2.0-dev-bin_2.88.0-1_amd64.deb' \
      '6ad683b9aa098745e3795d0126b087fb20d7632ea7f288ae1477ef69ba338c65  liblqr-1-0-dev_0.4.2-2.2_amd64.deb' \
      '6b066ab912300b2c6a965a9a8045da45c237a52b76c2c11d8f2ceaf7aabfacbb  libgprofng0_2.46-3ubuntu2_amd64.deb' \
      '6b5b60a5c372b6e9d1dcfa1507317aae59bf809d4f4d6d363d3ef0a58a189137  gnu-coreutils_9.7-3ubuntu2_amd64.deb' \
      '6bd25c936289463c6472290d3b4377edf8dd4f5e3a07f356fb0adf2de04a8055  libhwasan0_16-20260322-1ubuntu1_amd64.deb' \
      '6beb06e118c5a49abc312d029d6dc1ba47009e51a284d598bf394465522292f2  liblcms2-2_2.17-1_amd64.deb' \
      '6c0b2dd4654db30449754e6e1adf84a34d8a8d7dddeb75f8c9c463ad86645274  libxau6_1%3a1.0.11-1build2_amd64.deb' \
      '6c8def1cafec89468fef8bd0d7a4eb66192a7850bf17c9decf7bca8fcf3dd5fa  libc6-dev_2.43-2ubuntu2_amd64.deb' \
      '6cc74000944d3e8b0da9349ff49024e47996770745d194b2419eed43c59ce300  libfftw3-dev_3.3.10-2fakesync1build3_amd64.deb' \
      '6d2d873d2a77a76ea2a156c15a5ae798fe3711d8736cd2ff3872f53d57567e0e  poppler-data_0.4.12-1build1_all.deb' \
      '6d81369284ba3fd094f635fe6b9f8dfc71baaca36c1f758fe62244839e25ecf0  libzstd-dev_1.5.7+dfsg-3_amd64.deb' \
      '6d9aef9116d8b055e3fd50d6b80cf69e61b2c8705246416d837c587f7613103d  python3-packaging_26.0-1_all.deb' \
      '6e0ee5877c0d27b0d8fbe36387035e8f03074eed055112595ab2e85ac8b5711e  dpkg_1.23.7ubuntu1_amd64.deb' \
      '6f594146dc6f5d77694811c38c6743a99424e5bdd2e955afa82fcd19883f42cc  libffi-dev_3.5.2-4_amd64.deb' \
      '6f80b42ba84d5a55e4d3cf1850954bc2e37af585d47fc85721c8928f3c4c98e6  libxdmcp-dev_1%3a1.1.5-2_amd64.deb' \
      '6fb2dd68379bf9578af5ead58203ab322e3b1cf3a6f9562a1e4d12c18e923bfc  gettext_0.23.2-1_amd64.deb' \
      '707572352c05ef47816d4abe1c299172d29b22c096eb6cd56494997223f79b99  comerr-dev_2.1-1.47.2-3ubuntu4_amd64.deb' \
      '716e082f8b472d7447d394913ddf0067ab60b31f35ef014dbcecc610e6560e93  libfftw3-single3_3.3.10-2fakesync1build3_amd64.deb' \
      '72ba4fc43155566b46442b741a6892d5d1f1581ba58cdfd037aabf47ad9080f7  libfontconfig1_2.17.1-3ubuntu1_amd64.deb' \
      '732d29df36204d2f98ff22fab310e2452308dbe0e749e6d39733efcc8753c441  libgraphite2-dev_1.3.14-11ubuntu1_amd64.deb' \
      '7393f33be5584941bcfbd03a25901058c708046ee5dded01c21d56652a2d0eb7  gcc-x86-64-linux-gnu_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '74091083c33728c7a60bc95025bcad00569164cad7424bb2294b34361886d5a9  krb5-multidev_1.22.1-2ubuntu4_amd64.deb' \
      '74defa71b7f81d66b103afccfce750ad356976696b40c96c846ddc956fcfe937  libmpfr6_4.2.2-3_amd64.deb' \
      '74f9974205539e66b5e8ac1df326dc252c90c6816a5decae03a32df745d252f8  libseccomp-dev_2.6.0-2ubuntu5_amd64.deb' \
      '7562e7f3c551b2e005d71c5c20c5f34fa9d7926bf93e7eae4ab0a9f0ab061232  libperl5.40_5.40.1-7build1_amd64.deb' \
      '75d0c4c28732f8e08d5da25a47676dbe923e4b15a8f7a77110ab370325889df5  libpython3-stdlib_3.14.3-0ubuntu2_amd64.deb' \
      '763a89b5c40942860f4d000499579763a2123c1226b3d2a66677846aa304a85d  libaudit-common_1%3a4.1.2-1build1_all.deb' \
      '763fa3325cb0cb5dff197ddfce2671da824c8af9ddb98a585c1fad0419870124  bzip2_1.0.8-6build2_amd64.deb' \
      '76b4096fd9476d8d2eec24c6bca8fdfcab108a72e33f0fbcb47aa5cb7ef8de87  libpcre2-16-0_10.46-1build1_amd64.deb' \
      '76c5d9e1c631d51e299cb3ba59eea733c34297c79f86a73f0cdc1b49509a39b3  gir1.2-gly-2_2.1.1+ds-0ubuntu1_amd64.deb' \
      '76e64dda8fcbc3c04437085b01b0761552d9b4e7e90817aa56d478b275619736  gawk_1%3a5.3.2-1ubuntu1_amd64.deb' \
      '77cbd0ddf7e7487079ec300ff7751322de5e7d67f0f46749591b78ff1442cbe8  librtmp1_2.4+20151223.gitfa8646d.1-3_amd64.deb' \
      '77f8d49c031182bbd6c4fe4ec9ad49edb5d4607f2dac795fc6932dce0e8f541e  libacl1_2.3.2-2_amd64.deb' \
      '782f30c04eb7adf12f41d88663ff39b15b353a0807383e854941ce942c1f343e  libcups2t64_2.4.16-1ubuntu1_amd64.deb' \
      '799885145fe5982478fc53ce0206072a7dd402d6e42f5f7a951a78e9e49bcb84  gir1.2-pango-1.0_1.57.0-1_amd64.deb' \
      '7a9d4ce17f45d687ed38758bdc79efc8b5c7d79987dc5298de25961691b6bd09  bison_2%3a3.8.2+dfsg-1build4_amd64.deb' \
      '7b8fcc3d8b20ef353f7407f7f399c075d1a042c1e9b46874faa838f65d715a17  libraqm-dev_0.10.4-1_amd64.deb' \
      '7c25ce41fc15cd737664bea334cd941ecd0c64b3f51523c44c51254e7dfd7926  python3.14-minimal_3.14.4-1_amd64.deb' \
      '7c4eda2df18225fd80a8c72a9cda809cdbd16b1f799bd7751c76f30b4fc0c72a  libharfbuzz-dev_12.3.2-2_amd64.deb' \
      '7e643e76063b94df9159c8b8fd4b8bf53d2fbf119c9889a5cc6842b6be272e4f  libx11-6_2%3a1.8.13-1_amd64.deb' \
      '8188c233d59dc419205c314ef8f230fc83ca7a3e7e9b9671f18b469fd3e428ae  libx11-data_2%3a1.8.13-1_all.deb' \
      '8237f5a3911ec103734ad7636235515df9ba0f1506385f782e264d07d32757c9  xtrans-dev_1.6.0-1build1_all.deb' \
      '823df284bbc343ae6e22d69dc14a39c31b6c81fc2bccdd9ed720b88af92fcfa4  libdb5.3t64_5.3.28+dfsg2-10ubuntu1_amd64.deb' \
      '82d4aba3490578089d399921bf6444ad848468a23f2cb37262625b28e3615a76  bash_5.3-2ubuntu1_amd64.deb' \
      '82fa61135e7154d7958feaa91ec1808a688eb1e0e06822ab35e99e2480feb148  libatomic1_16-20260322-1ubuntu1_amd64.deb' \
      '839c57d360ebb65fbddbf4268a4594ef85a0ea8d982d92a309f7d25f17714d39  login_1%3a4.16.0-2+really2.41.3-3ubuntu2_amd64.deb' \
      '83a2a924c11759a2ed6e6f98f456d28e1b026974ce9e6e7ef12c9ac43b2d543e  libnettle8t64_3.10.2-1_amd64.deb' \
      '845aeb1b086d64d40e673ae80cbf971bcfe24e393ceea12f80ccc294b60ae621  libavahi-common3_0.8-18ubuntu1_amd64.deb' \
      '855e4f4a543789a427ad9aef77a31fbf99aebdd33576caa467e67a4301cd2d20  libmagic1t64_1%3a5.46-5build2_amd64.deb' \
      '85652c6768b45bdb16e38c022c7bbb8c103fba67135862bfed82f6d3f458a332  libjbig-dev_2.1-6.1ubuntu3_amd64.deb' \
      '858242571fc2585c1f8eb83ae01d020f0f4a92679d0de8fe31146f6687bdd84a  libbrotli1_1.2.0-3build1_amd64.deb' \
      '858a1ddd299cff3932bcc7085d16535f5b5140d15f6d84bd1b94b4a2a6c456b2  libcurl4t64_8.18.0-1ubuntu2_amd64.deb' \
      '85aefc091871221e4aa08d86615dd0e5140380928452418bd1e4e5226fee4628  libraqm0_0.10.4-1_amd64.deb' \
      '85e80dc9d475a40974607b0c8aa2d5bf761c1cebc0396ec2c54a6cb7d50fe330  pango1.0-tools_1.57.0-1_amd64.deb' \
      '85ffc97dcc6c63c80693b07a984128b9e267992482f12e1c0dd87c65f014c769  libc-dev-bin_2.43-2ubuntu2_amd64.deb' \
      '866fd07f5d3367fa42f1b0957007478b110f30918c08bedff566a2d6217bc3da  libcurl3t64-gnutls_8.18.0-1ubuntu2_amd64.deb' \
      '8673a23519f570b4a5b4a663a9ce3b0e2f0be50c7250ce7fdae19eb064c3d6aa  g++-15-x86-64-linux-gnu_15.2.0-16ubuntu1_amd64.deb' \
      '868203a25c631d588b8c36af969c836c7746dbf88af8c44fe5ecd7e64c1ceb3b  libopenjp2-7-dev_2.5.4-1_amd64.deb' \
      '86bcb6fb96b1f2f429741af853c7817982edaeae114a5162e8aa681cf3d2b596  libglib2.0-data_2.88.0-1_all.deb' \
      '8883a2bd236e54af0af33d7115835929c959bc50fd02ba63496ab6908b0c204a  libglib2.0-0t64_2.88.0-1_amd64.deb' \
      '88bfe1faddda7b905746429af8ee26ac5ace881c8fb9a994de8b54572445e728  tzdata_2026a-3ubuntu1_all.deb' \
      '88c0163f1acb384abde07641b7e13fcaea36e0a3b88fc57a653779fc429fc46a  libunistring5_1.3-2build1_amd64.deb' \
      '8962dd41c2cfad888d541a35e7c25d9e7456ed75e7d57c490156db4a8d8fdfee  librsvg2-dev_2.61.3+dfsg-3_amd64.deb' \
      '8a10cc3e38d8f85992d3ad5b3375ebb4214d318c92062bec955e4429edbc3a00  libx11-dev_2%3a1.8.13-1_amd64.deb' \
      '8b4e74f6fc7c9a08956f1430fe5d80f4d8970a08fe24df9e187d57753f652c7a  libhwy1t64_1.3.0-2_amd64.deb' \
      '8b59e0e881059cecebdbcdc6846f6626196c6085a476da8acde6f05e26661b02  libkadm5clnt-mit12_1.22.1-2ubuntu4_amd64.deb' \
      '8bbe8a6337529462ce0f188a98e5be5a7ae551bae6a9bdf8f0eb92c5d84f7c22  gir1.2-glib-2.0-dev_2.88.0-1_amd64.deb' \
      '8c14223ae11b2bba96afa0a1a08206cc63ad220d999e90a119f7c76549c62e16  libevent-2.1-7t64_2.1.12-stable-10build2_amd64.deb' \
      '8d2b4be34ebc5aeeae0b92506a8a13941a47fe39e5ef4ea767981b50ac638a61  libpangoxft-1.0-0_1.57.0-1_amd64.deb' \
      '8d3a361e8655a0ff4a390243059949fa6f22d42d0e266f58b57c124eb21d2993  libldap2_2.6.10+dfsg-1ubuntu5_amd64.deb' \
      '8d4b79897515b1da2e79a8a0364d15c64299d5e052e833d289c3a6738da2b337  libgraphviz-dev_14.1.2-1ubuntu1_amd64.deb' \
      '8d996790c80f2ece3f8885708e051966b3e6e427f919bf259e3282e1f7286041  nettle-dev_3.10.2-1_amd64.deb' \
      '8f0d18029ed6918c8a422c8108d5efe6bc3a0e264dc65844b47132aad426536c  libsm6_2%3a1.2.6-1build1_amd64.deb' \
      '8f20cbe794f047391f64453da3f67b91bf18e08e5ea66e47f144d397eea857e5  gir1.2-freedesktop-dev_1.86.0-6build1_amd64.deb' \
      '8f31234bf98ef4ba4d6a55155a340599920840c3aa7100853a8e9bd60c382257  libxcb-shm0-dev_1.17.0-2ubuntu1_amd64.deb' \
      '919b209f5040c1dca1d9c3912521e4bc476028c2e16905ab09347004a599a722  libldap-common_2.6.10+dfsg-1ubuntu5_all.deb' \
      '91fa094c31783f7ccf0f0df8ed06447655c40476ba61fc95dbd245a313f8171e  binutils-x86-64-linux-gnu_2.46-3ubuntu2_amd64.deb' \
      '9277da0b7f23a1611270a8e10b3132553aa20fc80202e1bd7e0ab30d2c3aafb7  sed_4.9-2build3_amd64.deb' \
      '929dfc0b2f287fd55918a5e07da7f0df05c4daf87ec3c9d7c27141d6e08fbc42  libgio-2.0-dev_2.88.0-1_amd64.deb' \
      '92bdac0f443a648859d06dee3defb9c96864fd76df6cfe617ca70bb261344767  libidn2-0_2.3.8-4build1_amd64.deb' \
      '936619071dd5d81ff672b685af9ad20e1f524be2241cbd80556aedc376844a36  libtext-wrapi18n-perl_0.06-10_all.deb' \
      '95b7a9b63096840cb960562d190a802a541055366eb4bc756c763d7de6e174d8  libtsan2_16-20260322-1ubuntu1_amd64.deb' \
      '95e7578d5fbed305f8a845b6d70c75166c692bee485ff729bc398c5c63c5ecef  libfftw3-bin_3.3.10-2fakesync1build3_amd64.deb' \
      '968b0e503f877a81c67bf82b634973e73901f6c4f4c741b5ec09824120791cd3  file_1%3a5.46-5build2_amd64.deb' \
      '9690471f395b6652f2cd8962334b9400e26a10daf4af7bf2f2c1a0325c193f0b  pkgconf-bin_2.5.1-4_amd64.deb' \
      '973d947573a467c36c1ebb3cbf31e134d4d2bdcf9cf2f4711613800749d434d0  libcgraph8_14.1.2-1ubuntu1_amd64.deb' \
      '97e8c7ce05e09ea5b766c99f4d77e20cb70db61396c2e83bb43715c6e2f0ac1e  xfonts-utils_1%3a7.7+7build1_amd64.deb' \
      '994595dcff5f8cc736d70a4798314006dce41da34d95511786039239440669f4  libgirepository-2.0-0_2.88.0-1_amd64.deb' \
      '996d76b48a389f74a602afa8c266f541934de027b54ab8ef4bb4ca118a6c751c  libthai-dev_0.1.30-1_amd64.deb' \
      '99b6836d1068436e7f92cc3a7b2c2c0efddeea12dc50c16a727f45bc044d4393  libglycin-2-0_2.1.1+ds-0ubuntu1_amd64.deb' \
      '9a400597b1db45cf51238c9eb556e211ec092d363cfb7ebebac627750ba56433  libstdc++-15-dev_15.2.0-16ubuntu1_amd64.deb' \
      '9b071ec8637a7d87e152eee7952df8f3374e432bafecd3bcc30948feb3acb3e9  mawk_1.3.4.20260129-1_amd64.deb' \
      '9be071fbb1cc4cb311d477456dbe4e1e97ae9b46468cff51b015c76700da9887  libxcb1-dev_1.17.0-2ubuntu1_amd64.deb' \
      '9d23ccd2a24d8618ca8bc7f1e14e1d02b9632854d69c82b6f8753dc5c1a98b16  pkgconf_2.5.1-4_amd64.deb' \
      '9e99ba57e776dcd8861a8f89be4fe439ea86bd577a2695b9aed34785bba05fac  libdatrie-dev_0.2.14-1_amd64.deb' \
      '9edd0db0fa94580ab013529d6842a8e89b8ed22ab337da5e95cbb43971978815  autoconf_2.72-3.1ubuntu2_all.deb' \
      '9ef16e373319feb10fa112eec5d906b302cd2c7b870af231f347d96d8db549e8  sgml-base_1.31+nmu1build1_all.deb' \
      '9f65ccd8b1afde140286b2890064bb1119afabc5aead01ed0aa741134ee8cc94  libijs-0.35_0.35-16_amd64.deb' \
      '9f921930903e1dfa626593a411dba2146c91cdacce724f541a079b181452ef41  libpam-runtime_1.7.0-5ubuntu3_all.deb' \
      'a0332ff93980b20429464cd7bf906badab8c4f79065ee7422b6278081a423f3f  libraw-dev_0.21.5b-1ubuntu1_amd64.deb' \
      'a07ad7d60c4ea78da6b849e04ae667490ddbe7b10e96c1c5d41526d9144dd095  liblcms2-dev_2.17-1_amd64.deb' \
      'a0d9a3f3caa5d924622f31ca24f64a13526785f67ef4453c41dc8a24afeb19dc  libunbound8_1.24.2-1ubuntu2_amd64.deb' \
      'a1b3327d907ac5c2fab020f67b26abcc325516abff3db8fa38fb1e2221c1934b  libcgraph-dev_14.1.2-1ubuntu1_amd64.deb' \
      'a22daa89e8502e179401b693bb2fd0718d4cb45798aade391a393e14146d7320  libimath-dev_3.1.12-1ubuntu5_amd64.deb' \
      'a306b64c3019f401686e76a361b85567fe3ed1edad1f556dc9b14fa072c91056  xorg-sgml-doctools_1%3a1.11-1.1build1_all.deb' \
      'a30fdde4eff9088eb91050856b58b7a87abc668a1d88895a9ee670c76f091cb0  libsmartcols1_2.41.3-3ubuntu2_amd64.deb' \
      'a32b9ad585e39bdc7bd15d1eae6293461e6d466859a1dd2f7862d1e40f89b9d8  libstdc++6_16-20260322-1ubuntu1_amd64.deb' \
      'a385713732a7411d39ba5c057f8e5727d0cdf3bf8afa36cbe1104c66ae2acd5b  libpcre2-32-0_10.46-1build1_amd64.deb' \
      'a4343a8c026e1ca8e2e76a5d01abb8c2d6381961a1766b2d2363e3e23cc362ca  e2fsprogs_1.47.2-3ubuntu4_amd64.deb' \
      'a4d8d0682aecb3a9414d8938518f48d4d7433239172b7fc1458eb9690b75a323  libfftw3-double3_3.3.10-2fakesync1build3_amd64.deb' \
      'a6ad7fd2294e8e04d553919b5beed0269ebc6f73d41261ed1059c7fde83227f0  libxft2_2.3.6-1build2_amd64.deb' \
      'a75356fa8e3234a6e7b42d27e999f3071bd84e1349146916d90aa325343035fa  libheif-dev_1.21.2-3_amd64.deb' \
      'a76ad9102039122ef72b01c9c364e7d8967331414cbe19151c01d1391ff9fe25  libfreetype6_2.14.2+dfsg-1_amd64.deb' \
      'a7dbf52e62f1bcba20502bbb1f0b7f86f096f9c41860f62158241ac4bc2ebf22  libdeflate-dev_1.23-2ubuntu1_amd64.deb' \
      'a800a05f9e22011add40fe7deef712be53c721d9e23281bfd07ede46e514dd45  x11proto-dev_2025.1-1_all.deb' \
      'a86f39d57a32b7c919c0ad721fc2f17ab533a42fda348c8d81a4eea1577a014f  make_4.4.1-3_amd64.deb' \
      'a95109fde453f2c43027b6babfb395f2e037c65b901aa69aaaef5e3067b0b93e  libcurl4-openssl-dev_8.18.0-1ubuntu2_amd64.deb' \
      'a95c75b486f26fe8b140a632fd9e2883b7e2efc21f7586e155d27d2d2ff0ddc0  libmpc3_1.3.1-3_amd64.deb' \
      'a989e666bb0d64636a10a1253c949f92a282782d79d1725e0e1acc17282909a5  libpangocairo-1.0-0_1.57.0-1_amd64.deb' \
      'a9bbe9d4a4bcd5875bbd0f53e67c379bc881d1c1a80522d51dfb4b107cc31819  libgmp10_2%3a6.3.0+dfsg-5ubuntu2_amd64.deb' \
      'aab1f05de965b5f45af845ef45e276bcf53d811804633728bf540c58391a8bd3  libgnutls28-dev_3.8.12-2ubuntu1_amd64.deb' \
      'accd0695703203d9b50cc6325e7f7e849875789cc1f55ba975651e83e3045a76  libsemanage2_3.9-1build1_amd64.deb' \
      'acf0babd7e2da02a1f03981398624f7ad4660eb1ff188b4c9e93a350f98d02cd  libpam0g_1.7.0-5ubuntu3_amd64.deb' \
      'ad08194ced9e6ce211ad551712a97b95cf64f2a970179544b7ad428dbe3d3a46  libharfbuzz-cairo0_12.3.2-2_amd64.deb' \
      'add19738c63794d2aa9ac529d3b8aebe2e88980faecb6c1c59f07aefd6c3c314  libgomp1_16-20260322-1ubuntu1_amd64.deb' \
      'af1d01163b01f45a027054c3e0bcdadf01d5d318b8b9ffdcaa13c01ec4e2f2e7  librsvg2-2_2.61.3+dfsg-3_amd64.deb' \
      'af304471211e20de8e4271b6d60ca6a6286825d1668f24e007364712d1787d47  libheif1_1.21.2-3_amd64.deb' \
      'af502a90b8bf5c018e04feb0bba482ff9a5c81cfc5291aa4585e394b486d78c8  libaom3_3.13.1-2_amd64.deb' \
      'af7be2be588d15a16c696ab43ba3e92bd5f9a6850e8780234059b02a67716e58  libdbus-1-3_1.16.2-2ubuntu4_amd64.deb' \
      'b03241fd8fcee4ee829ebfecadf28799ec7da36c2e0ab49f2626def937a1f4b6  gir1.2-freedesktop_1.86.0-6build1_amd64.deb' \
      'b0dd63141194c49e026036a06f21a7e05f2e5080e3909e4043a29e8662c4d4c9  libsepol-dev_3.9-2_amd64.deb' \
      'b1def6b47f4f45852e4f79127fad9b947e2b9c1d5e2282e986b8bdb0ddd51b24  perl_5.40.1-7build1_amd64.deb' \
      'b2d8c9534c882635737371984a4beec5275c8431d9022c7b6ecbe6d0a4af73b2  libssl-dev_3.5.5-1ubuntu3_amd64.deb' \
      'b4255d5aea7986fa06ae3a3599f9e5c38a58ded1c3b79cfaf3c2959ad160eeff  libxt6t64_1%3a1.2.1-1.3build1_amd64.deb' \
      'b43e38f2d5ae4aa38471e1b3f90ed63e96c2ce614ffe496cdcd72f9944e87a4a  libgmp-dev_2%3a6.3.0+dfsg-5ubuntu2_amd64.deb' \
      'b4b0b4822f5cae347a6ed288adb60a8ebb2f9ea9ee66469e4a810f48b89a87aa  gir1.2-glib-2.0_2.88.0-1_amd64.deb' \
      'b85648bbdaec921ea9c59be7c7bfe0ff478269678d133838ff24a72b5294dfe9  libtiffxx6_4.7.0-3ubuntu4_amd64.deb' \
      'b867ba9daa9437ba3f18cba9646d9e3db55e5197bd4feb53184b1414c05210ca  libxext6_2%3a1.3.4-1build3_amd64.deb' \
      'b96f99f7964c0768c4f421b5aab71d03a25a749695c4058ff0304a101fcf1870  gzip_1.14-1~exp2ubuntu1_amd64.deb' \
      'baacc9086e17c8cadc3603365e660f907bca483de4446e56e6f1bc25da4c02be  cpp-15_15.2.0-16ubuntu1_amd64.deb' \
      'bb2ffa4e359ee7a29dab9902b45e5c85de06f019272700cb2538e4762f141ee8  libjbig0_2.1-6.1ubuntu3_amd64.deb' \
      'bbf4b3ce29246fa95ce6d62cf3f1d82bd2ca0c0e32e3ed5c1738118f9bf6b480  libpathplan4_14.1.2-1ubuntu1_amd64.deb' \
      'bcba1775a914698ba5270f0febb1c47a3fceede86b17c574550d84e0b581dc0f  libkrb5-3_1.22.1-2ubuntu4_amd64.deb' \
      'be59254289c670d5c6580ce381995292aa05c9dd4bc5fa65b9dbaa527b55adda  fonts-urw-base35_20200910-8build1_all.deb' \
      'be7c90d171aff0597b35ebdb2eefd5a4a8e50a444bcb81ad43c2d120387d3cfb  libgs-common_10.06.0~dfsg-3ubuntu1_all.deb' \
      'bea5eec4d84ae0c145cc32cd15e2ec7c458e66cd16b3b8cf4656e0966e437541  libxcb-render0-dev_1.17.0-2ubuntu1_amd64.deb' \
      'c0279172b218093c674151044326457f6cb3e2ce0b1241380e3897e65677283e  libltdl7_2.5.4-9_amd64.deb' \
      'c06f206be1ef7aa8208110b38945205ebc742dd777cbb39142baa555fe61390a  libthai0_0.1.30-1_amd64.deb' \
      'c0a3ffd95125ef0f12b4c38993f0485738f3a97a4ecfc663aae6b274b4384b0b  libdjvulibre21_3.5.29-1_amd64.deb' \
      'c0bd8dbe186941f2aaf2b1536d1b48084a7ceda68369afb7f66391b9bcacba36  libmount1_2.41.3-3ubuntu2_amd64.deb' \
      'c13775dc0c984403f3fcad229d14507a9f387763bd07ace1e5f93897ee6b8434  libc6_2.43-2ubuntu2_amd64.deb' \
      'c1e08ebf03feded26a42a0f07f94789e5995b402d704d2faafdc86fffda0b28b  libpangoft2-1.0-0_1.57.0-1_amd64.deb' \
      'c1f76915a74cc57361b51643f71862c3a134f30bcb3cb6c70286a855d600d564  libfreetype-dev_2.14.2+dfsg-1_amd64.deb' \
      'c2feae172b14d2a8317348023c5e0b6572314c097a9f7b8225c62b0988cc8d92  libelf1t64_0.194-4_amd64.deb' \
      'c32b43a862d1e2d581cb7ec7d2e7834fddd864f14a9a3804a3a3574f2bd9cfd8  libxdot4_14.1.2-1ubuntu1_amd64.deb' \
      'c34230e6892fa95e498e51640f7131946120b83eb672f586e341fa53bf504359  libc-bin_2.43-2ubuntu2_amd64.deb' \
      'c3a6880fee02053cc4652e694f5fe55e102af94f4d8755a43cee337a24ba46a5  uuid-dev_2.41.3-3ubuntu2_amd64.deb' \
      'c3b36d7357dea773eefe6c4f97ebff416e5afee22489dc1f729e31d6f47872e9  git_1%3a2.53.0-1ubuntu1_amd64.deb' \
      'c45bbbf9c87457d90b8ba38720c5f01b9388c380d40f303c26f5c4953932da26  zlib1g_1%3a1.3.dfsg+really1.3.1-1ubuntu3_amd64.deb' \
      'c5098ddcc5f5b001f216a08b92945d887bf6ebf66130835bb5be3df8262a2a44  girepository-tools_2.88.0-1_amd64.deb' \
      'c50f964c501984568fc48b2a095245a2e4d14165671f9ff8e7be36c2384278a2  libcdt-dev_14.1.2-1ubuntu1_amd64.deb' \
      'c52ecc664e968b347d47184d77f2d8bcad3ee4ffbbd328b6d1066b147af42766  libheif-plugin-aomdec_1.21.2-3_amd64.deb' \
      'c5e4b198f251da0ede226fd179830bd8767482821a1773f835358f726795cb16  libseccomp2_2.6.0-2ubuntu5_amd64.deb' \
      'c711670008478b8605efbd49184df584b7f1771d3cddfcb3cf545213e7784b16  libjbig2dec0_0.20-1build4_amd64.deb' \
      'c8b97930f9e365d6d00978144b468ac8397ef07d2fb2c453869f05fc3a98c4ca  libicu78_78.2-2ubuntu1_amd64.deb' \
      'c90895d3b6cd164fcb54def68c7dff74419f869c837fa607e3f54c1a0e742263  liblsan0_16-20260322-1ubuntu1_amd64.deb' \
      'c98809a1473c93b5390f057279091ff2685c8b1012f5cce56146df5950b8f3ad  libpixman-1-dev_0.46.4-1_amd64.deb' \
      'cb7771861d821e48d38253f2397217920d5cf8020ed9de8372a625d080dcc6be  g++-15_15.2.0-16ubuntu1_amd64.deb' \
      'cb85c869fe056e9e466efcfa3403408b0a87db1da1cafa585140a9be59fe58a1  liberror-perl_0.17030-1_all.deb' \
      'cc2870c52d3d6845bd792e861930dd6afc5fe165edb0c8c3700332c3bfbd666e  git-man_1%3a2.53.0-1ubuntu1_all.deb' \
      'ccd902384546225842384de0c46dad4670ccdda17b697bed4518610ed2e08e89  libgdk-pixbuf-2.0-0_2.44.5+dfsg-4ubuntu1_amd64.deb' \
      'cdb2383bd9c5fcdb0809943ecd21b11cb2da60777d345f052eda7672c1718e7c  libfontconfig-dev_2.17.1-3ubuntu1_amd64.deb' \
      'cde09806b1b60d0ab8ab96033177cb21a0290333a946f25572de8f72b4403695  libubsan1_16-20260322-1ubuntu1_amd64.deb' \
      'd14fc7bf644b495083f77c99ff168f1a2215c8b3b7ad5202e0345dc1092002b0  binutils_2.46-3ubuntu2_amd64.deb' \
      'd2328ad5c97b9df2decbfdcd3a849cbf38f6c823aa96eef7fe2143b791aac96f  libnghttp2-14_1.68.0-2_amd64.deb' \
      'd2b6927cdf61e51461542b3e167d3257fc91ca5c194f9ab2e681cb8abebb99f1  ziptool_1.11.4-2_amd64.deb' \
      'd3b8aa4efc9851ad9641ef2b1cc13d125c7c45d167e53527c694255d0c47b68f  libaudit1_1%3a4.1.2-1build1_amd64.deb' \
      'd59b3a851c0b58759e9f940fa407f68a6ef46401381e5389c74e5ded5419262d  libasan8_16-20260322-1ubuntu1_amd64.deb' \
      'd5d51e67063ff11e81698d8ee90bab5af763dc0a793929f33712bb74e7633768  libxdmcp6_1%3a1.1.5-2_amd64.deb' \
      'd5f37616b30209d8c10c4a705d7bf9558ca21e058fc2b2bd2ffcf37a74a42861  python3-minimal_3.14.3-0ubuntu2_amd64.deb' \
      'd7102b9d3fd35fd7a66d94ba0765a9c8e87b2b80e3633ef4af401dd0c952bafd  rpcsvc-proto_1.4.3-1build1_amd64.deb' \
      'd755a3f99a4895165703aad60ff15cf931e04da41b35facb15393d7d4b2c0242  libice6_2%3a1.1.1-1build1_amd64.deb' \
      'd780844418b745c432a5d6c85f055625f37e27523b026baee0c87d386a0aab0a  gcc_4%3a15.2.0-5ubuntu1_amd64.deb' \
      'd7e159946170bacac86879d205190f0de4fffb9a1ea2feb18b509c2c76e742f0  libavahi-common-data_0.8-18ubuntu1_amd64.deb' \
      'd9eb011adc50e75fc8feea6725b2de0faa9f28e71b77bb047d483cf54987bfa7  native-architecture_0.2.6build1_all.deb' \
      'da2eb52074c56dc60f6e446166ad799baa9a53e619971debd033e99ed37f158f  shared-mime-info_2.4-5build3_amd64.deb' \
      'da684bb562e167721ae38366586aaee0b4cc580b9ee6d0220128b15ef9c5be75  libmd0_1.1.0-2build4_amd64.deb' \
      'dbcd534015145129d70d00afb2c582caded324b9fb6e18ec3720f4aa9e879443  libsm-dev_2%3a1.2.6-1build1_amd64.deb' \
      'dca245ac780cbdd61d6a8b148b2f582ef2f4d051c42978925d6a9d32730fe338  libkrb5-dev_1.22.1-2ubuntu4_amd64.deb' \
      'dd4d9812c035d6731229650c6860a07586961c2ac491de622032a338ba0129f0  libsysprof-capture-4-dev_50.0-1_amd64.deb' \
      'df0e5375c9e981b18e396c2e9ec1e359f226576a9b94a311bf07603f3ca6023a  gcc-15-x86-64-linux-gnu_15.2.0-16ubuntu1_amd64.deb' \
      'e0712227152b5b9d0233a4136a7fafc04870c0d8aee45914836a16923b372656  liblqr-1-0_0.4.2-2.2_amd64.deb' \
      'e0848724d39a0519bc781697d9827cf87013a423632be2208e4afdef190ee788  curl_8.18.0-1ubuntu2_amd64.deb' \
      'e088ea3497fba3ab7940ddaa4db7639f352b555871235e5600d213725d5e14a3  libraw23t64_0.21.5b-1ubuntu1_amd64.deb' \
      'e0c61b3720cb4cbdc60e6063d59b02a48375dee10ee9de2113cee368ae27b416  libfftw3-quad3_3.3.10-2fakesync1build3_amd64.deb' \
      'e237988a0afaac805352f346cf035783b3e2643504e0c0f73eae8f9e21669efb  libwebpdecoder3_1.5.0-0.1build1_amd64.deb' \
      'e2fd1b1255b379040d8931074447ab30a971e941bca053a480d4c26310dda002  libglycin-2-dev_2.1.1+ds-0ubuntu1_amd64.deb' \
      'e3af297b2131aea35eab7e2751b4158ec7ae4ffb6d746043199f766fc727744f  libpng16-16t64_1.6.57-1_amd64.deb' \
      'e4da6abdb642623afd2e4a60ef354539f8b74ba0f2daaaeb0e058a392d4ae571  libwebpmux3_1.5.0-0.1build1_amd64.deb' \
      'e667f3a89b8237f15f43bc837f1f6606fdf5164a7670338573a4dc16a04c0fb4  libpaper2_2.2.5-0.3maysync1_amd64.deb' \
      'e70d3422e24b267293215134458f340944bf10e92b27147594c69a7dd2823089  libp11-kit0_0.26.2-2_amd64.deb' \
      'e70d52936aabd7a90e9cd8af0f54ca050cde244f8382ffc5524ba65117c199c4  libxcb-shm0_1.17.0-2ubuntu1_amd64.deb' \
      'e91702d05c014768a85814efde45133b0e1a75faf1c8ff51a31563644229ffc6  gir1.2-harfbuzz-0.0_12.3.2-2_amd64.deb' \
      'e9329ba8c8c92b6cb10e3adf8bb75ed6289ada8e4f395550b3f1dc84f251f7ac  libgssapi-krb5-2_1.22.1-2ubuntu4_amd64.deb' \
      'e9ef750cc8ba426dee52f56aba0150e7e463b2658173bed8c4ca2927eec1c447  libgdbm-compat4t64_1.26-1build1_amd64.deb' \
      'ea447cab507c8672e27004be1447c438d0abb3188fffd28aa49381980b294501  libgdk-pixbuf2.0-bin_2.44.5+dfsg-4ubuntu1_amd64.deb' \
      'ea6f8b04b5902cbd1e33aad8a3fe78c7a18515d7ac6f9b67e0b03f5f8a23a285  libxml2-dev_2.15.2+dfsg-0.1_amd64.deb' \
      'ea7d3cc642ffe2459c35a85c894f80e92499b9eba13bdcb225e0aa751c0970be  libkeyutils1_1.6.3-6ubuntu3_amd64.deb' \
      'ea9d94da2fb6564391145f3a9630c140c8dd771a38ae753983e8dc55cc22e102  libuuid1_2.41.3-3ubuntu2_amd64.deb' \
      'eb155f0a9531b5f3b1c06e0e415c4cd7e01777e7714cf51ac094fa6afa01638f  debianutils_5.23.2build1_amd64.deb' \
      'eb5ba6fd4ec1a68801e757f4492c6c6b30119ff277ac9d99629a011559c963f0  libc-gconv-modules-extra_2.43-2ubuntu2_amd64.deb' \
      'ec2f5d6c903bad6b26d2b953489691b2e6f87cae66ff7bccbe61bb5f3b4b744c  libsqlite3-0_3.46.1-9_amd64.deb' \
      'ec93ea39ddeb5a98179b60eab4af234b6c676f1958106645d1f4b19280d4cd09  libharfbuzz0b_12.3.2-2_amd64.deb' \
      'ed00525d45980e5514b683b2e9d54293ed8e685d132dcdb3af9ad343000d77a0  librtmp-dev_2.4+20151223.gitfa8646d.1-3_amd64.deb' \
      'ee67d2df8ac299b20668d93c4817e9db88626b0636cc4cda76b1948e140e364b  sensible-utils_0.0.26build1_all.deb' \
      'ee9d40864d38d500f001aa78e0bc358d8d85e878c15c7e5ef7f38c320659cd65  libjxl-dev_0.11.1-6ubuntu4_amd64.deb' \
      'eee0f49c4c19e29df01aacbf3cbd06dfa29ed850c5ae186ff2ada49b2cc4807c  libharfbuzz-icu0_12.3.2-2_amd64.deb' \
      'ef20434fbf03076d238155e937870cf389884ae81bd8c3569ff6043aef6da398  libcap-ng0_0.8.5-4build5_amd64.deb' \
      'ef78089497946219cac03209d951bbfff93480104e791b770a7bf6429452e475  libexpat1_2.7.4-1_amd64.deb' \
      'ef841c269b5e9f324e38b1069f712a13c29237051f037847d1de79441dc3a9a2  libitm1_16-20260322-1ubuntu1_amd64.deb' \
      'ef8e6376ecdaa82f4f7fbd1f6fb8cbf7818a1305c8e7b015c1aa9f4bdc77d12a  zip_3.0-15ubuntu3_amd64.deb' \
      'f008e39aada379d64166153d5e37ccc4f18b3e334babb9e32c4da9b4396ee733  netbase_6.5build1_all.deb' \
      'f0243e2370cf86578de2659b4d1f57f81c2f9e7401dd13d183d51f60b139c1d2  libssh2-1-dev_1.11.1-1build2_amd64.deb' \
      'f0832941a48e3b4d487c94fba1708a70dcdadff9e9eb6604ec7645d71872fd35  libglib2.0-bin_2.88.0-1_amd64.deb' \
      'f0c87cee9a1fb871e66698dc05fe38e0a3e7232eb961b690a8e7dc26f9753813  libxml2-16_2.15.2+dfsg-0.1_amd64.deb' \
      'f2caf1f807c0b203e5f4545c3010ac34b2dd5f546704e5b1b9c62a41d483771e  libblkid1_2.41.3-3ubuntu2_amd64.deb' \
      'f3412d08032210541d25c4e00fa492ce527af245ac9bec2e543d81a59b4426aa  media-types_14.0.0build1_all.deb' \
      'f41108de5823fee85bd355a06b2939b2c8fe2f6df267c4fa45435544990ec6ff  libncursesw6_6.6+20251231-1_amd64.deb' \
      'f51d5b17d773b915618239b2741f7b792ca6b50bc33f8f5296894060af1706ef  libgio-2.0-dev-bin_2.88.0-1_amd64.deb' \
      'f7025ab9b24cd73215510931037b02d6960d89584d0d00afba81851abdbe6ef1  ca-certificates_20260223_all.deb' \
      'f8a985e1bc63f943db0ca9ada3309edfda4042a3023e36d80c6cf3e9591c557b  libk5crypto3_1.22.1-2ubuntu4_amd64.deb' \
      'f9cfb4ba27d0745cbfc7c064cc68f15ea3d6b144a4fd1da9c5f83fe30008aef7  libkrb5support0_1.22.1-2ubuntu4_amd64.deb' \
      'f9fdae226c125571bcee451a43ec62d895c996fb8b02e9c24e651f540ae34340  libgssrpc4t64_1.22.1-2ubuntu4_amd64.deb' \
      'fb7e1b31596661cc1f660608af09383eadc02c8574f2ddac8171956c123fab0b  libxft-dev_2.3.6-1build2_amd64.deb' \
      'fbad1d0e81e2b18602bce921697fa14c6dc54c09e790f917e1d512f1fb4c320d  libsepol2_3.9-2_amd64.deb' \
      'fc23170281e0455ab02ab8b0041eac4b3f46a3ae9df165c117999260ccbc093a  grep_3.12-1_amd64.deb' \
      'fd7926e9f22b1c6f0d408c18ec6f6961b279cfcc9772196eb2470e9d264b3b05  libopenjp2-7_2.5.4-1_amd64.deb' \
      'fd89943a93fdb3e2746faff8fe1bb23106dbdd6c891df0f50fe2f8b42d6f089d  coreutils-from-uutils_0.0.0~ubuntu25_all.deb' \
      'fdae0a5b58249fc43cd705eb6e8e20bb1e8af7dbb1fa3a90e90eb091218c5a28  hostname_3.25build1_amd64.deb' \
      'fddf95c7c5fcd2171a9a9096f07703b89359da4aee93919f79d7768b0e282b38  libjxl0.11_0.11.1-6ubuntu4_amd64.deb' \
      'fe2575ef6a1fc91c5fc6f50c866e24b773682136fa2b548ce0b28d68513b0e63  liblerc-dev_4.0.0+ds-5ubuntu2_amd64.deb' \
      'fe78b8124fb6c8c0d7efc8f2bd8d5e0d3f217351f520a3b4652ee0afe24143c2  libssl3t64_3.5.5-1ubuntu3_amd64.deb' \
      'ff18e8ae397fb6c49037ce632e299d0faccc8851cb19fb536fd3c1f26d911541  libgs10-common_10.06.0~dfsg-3ubuntu1_all.deb' \
      'ffc9f1fea544f200b7b47a77e0ec89f70d493b5393ea2f7a43f6b9685b3341b8  liblzo2-2_2.10-3build2_amd64.deb' \
    > SHA256SUMS \
 && sha256sum -c SHA256SUMS \
 && apt-get install -y --no-install-recommends ./*.deb \
 && cd / && rm -rf /tmp/debs \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Re-register the workspace as a safe git directory for
# the container user. Needed for any later git operation
# this image's consumers may want to do.
RUN git config --global --add safe.directory '*'
