#!/usr/bin/env bash
#
# slsa-autotools linux binary hook for ImageMagick.
#
# Builds an x86_64 AppImage of ImageMagick. Runs from inside the
# distdir produced by `make distdir`. Mirrors the recipe used by the
# project's existing linux_app_image CI job, with one key change:
# linuxdeployqt is downloaded and verified by SHA256 instead of from
# the floating "continuous" tag, so two passes get the same bytes.
#
# Output: ImageMagick-${VERSION}-x86_64.AppImage in the current
# directory. The release.yml caller globs *-x86_64.AppImage and copies
# matches into the artifact upload set.

set -euo pipefail

# Record entry CWD before any cd: release.yml invokes us from inside
# the distdir, and we cd away in step 1 to stage linuxdeployqt.
DISTDIR_BUILD="$(pwd)"

LINUXDEPLOYQT_URL='https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage'
LINUXDEPLOYQT_SHA256='974a87457ed26241b793bed7841978fcdf84158d13220e53833a06515f173b0b'

# 1. Pin and stage linuxdeployqt. --appimage-extract avoids needing
#    FUSE in the container; appimagetool runs from the extracted
#    squashfs-root tree.
mkdir -p /tmp/linuxdeployqt
cd /tmp/linuxdeployqt
curl -fsSL "${LINUXDEPLOYQT_URL}" -o linuxdeployqt.AppImage
echo "${LINUXDEPLOYQT_SHA256}  linuxdeployqt.AppImage" | sha256sum -c -
chmod +x linuxdeployqt.AppImage
./linuxdeployqt.AppImage --appimage-extract >/dev/null
LINUXDEPLOYQT_BIN=/tmp/linuxdeployqt/squashfs-root/AppRun
APPIMAGETOOL_BIN=/tmp/linuxdeployqt/squashfs-root/usr/bin/appimagetool

# 2. Configure + build + install to a staging DESTDIR. cd back into
#    the distdir; the configure script there is the one shipped by
#    `make distdir` (a copy of the autoreconf'd configure).
#    --prefix=/usr is the AppImage convention so binaries land at
#    appdir/usr/bin once DESTDIR is stripped. Flag set matches the
#    project's existing CI.
cd "${DISTDIR_BUILD}"
APPDIR="${DISTDIR_BUILD}/appdir"
rm -rf "${APPDIR}"
mkdir -p "${APPDIR}"
./configure \
  --quiet \
  --prefix=/usr \
  --with-quantum-depth=16 \
  --without-magick-plus-plus \
  --without-perl
make
make install DESTDIR="${APPDIR}"

# 3. Stage desktop file + icon. The .desktop and .png are not in
#    EXTRA_DIST so they did not survive `make distdir` — reach back
#    to the original checkout via ${GITHUB_WORKSPACE} for them.
#    AppRun is generated by configure from app-image/AppRun.in
#    (declared in AC_CONFIG_FILES) so it does live in the build tree.
SRC_APPIMAGE_DIR="${GITHUB_WORKSPACE}/app-image"
mkdir -p "${APPDIR}/usr/share/applications"
cp "${SRC_APPIMAGE_DIR}/imagemagick.desktop" "${APPDIR}/usr/share/applications/"
mkdir -p "${APPDIR}/usr/share/icons/hicolor/128x128/apps"
cp "${SRC_APPIMAGE_DIR}/icon.png" "${APPDIR}/usr/share/icons/hicolor/128x128/apps/imagemagick.png"

# 4. Bundle dependent libs into the appdir. linuxdeployqt walks the
#    binaries' RPATH/NEEDED and copies in the closure of system libs.
#    Unset Qt vars to keep its detection from misfiring on a non-Qt
#    project.
unset QTDIR QT_PLUGIN_PATH LD_LIBRARY_PATH
"${LINUXDEPLOYQT_BIN}" \
  "${APPDIR}/usr/share/applications/imagemagick.desktop" \
  -bundle-non-qt-libs

# 5. Replace the generic AppRun linuxdeployqt drops with the
#    project-shipped one (handles MAGICK_HOME / module path setup +
#    multi-binary symlink dispatch).
rm -f "${APPDIR}/AppRun"
cp app-image/AppRun "${APPDIR}/AppRun"
chmod +x "${APPDIR}/AppRun"

# 6. Pack into final AppImage. mksquashfs is PATH-shadowed by the
#    /opt/wrappers/mksquashfs that release.yml installed, which
#    appends -mkfs-time/-all-time/-no-exports/-no-xattrs/-all-root
#    for byte-stable payload across passes.
VERSION=$(awk -F' *= *' '$1 == "VERSION" {print $2; exit}' "${DISTDIR_BUILD}/Makefile")
[ -n "${VERSION}" ] || { echo "ERROR: could not derive VERSION from distdir Makefile"; exit 1; }
"${APPIMAGETOOL_BIN}" -g "${APPDIR}/" "${DISTDIR_BUILD}/ImageMagick-${VERSION}-x86_64.AppImage"
